//! The canonical policy encoding, against the vectors the TypeScript encoder produced.
//!
//! The EVM module keeps `keccak256(canonicalBytes)` as a policy's identity and this chain keeps the
//! policy itself, so the two have no reason to agree unless something makes them. That something is
//! `../../../test-vectors/agent-policy.json`: the same file `AgentPolicyCodecTest` reads on the
//! other side, generated by `@proofbridge/order-params`, which neither chain reimplements.

#![cfg(test)]

extern crate std;

use std::format;
use std::string::{String as StdString, ToString};

use soroban_sdk::{Env, String, Symbol, Vec};

use crate::fingerprint;
use crate::policy::{AgentPolicy, TokenLimit};
use proofbridge_core::rate_limit::{Bucket, Limit};

const VECTORS: &str = include_str!("../../../../test-vectors/agent-policy.json");

fn vector(name: &str) -> (StdString, StdString) {
    let v: serde_json::Value = serde_json::from_str(VECTORS).unwrap();
    for case in v["cases"].as_array().unwrap() {
        if case["name"] == name {
            return (
                case["encoded"].as_str().unwrap().to_string(),
                case["fingerprint"].as_str().unwrap().to_string(),
            );
        }
    }
    panic!("no vector named {name}");
}

fn bytes32(env: &Env, byte: u8) -> soroban_sdk::BytesN<32> {
    soroban_sdk::BytesN::from_array(env, &[byte; 32])
}

fn limit(env: &Env, token: u8, max: u128, capacity: u128, refill: u128) -> TokenLimit {
    let _ = env;
    TokenLimit {
        token: bytes32(env, token),
        max_per_order: max,
        rate: Limit {
            capacity,
            refill_per_second: refill,
        },
    }
}

fn policy(env: &Env, limits: Vec<TokenLimit>, ad_scope: Option<Vec<String>>, valid_until: u64) -> AgentPolicy {
    let mut actions = Vec::new(env);
    actions.push_back(Symbol::new(env, "lock_for_order"));
    let mut whitelist = Vec::new(env);
    for l in limits.iter() {
        whitelist.push_back(l.token.clone());
    }
    AgentPolicy {
        allowed_actions: actions,
        token_whitelist: whitelist,
        valid_until,
        revoked: false,
        settlement_signer: bytes32(env, 0xcc),
        ad_scope,
        limits,
        buckets: Vec::<crate::policy::TokenBucket>::new(env),
    }
}

fn hex(b: &soroban_sdk::BytesN<32>) -> StdString {
    let mut s = StdString::from("0x");
    for byte in b.to_array() {
        s.push_str(&format!("{byte:02x}"));
    }
    s
}

fn encoded_hex(env: &Env, p: &AgentPolicy) -> StdString {
    let bytes = fingerprint::encode(env, p).unwrap();
    let mut out = StdString::from("0x");
    for i in 0..bytes.len() {
        out.push_str(&format!("{:02x}", bytes.get(i).unwrap()));
    }
    out
}

#[test]
fn the_default_shape_matches_the_typescript_encoder() {
    let env = Env::default();
    let mut limits = Vec::new(&env);
    limits.push_back(limit(&env, 0x11, 1_000_000, 5_000_000, 10));
    limits.push_back(limit(&env, 0x22, 250, 1_000, 1));
    let p = policy(&env, limits, None, 1_800_000_000);

    let (encoded, expected) = vector("every-ad");
    assert_eq!(encoded_hex(&env, &p), encoded, "byte-for-byte, not just the same hash");
    assert_eq!(hex(&fingerprint::fingerprint(&env, &p).unwrap()), expected);
}

#[test]
fn row_order_is_not_policy() {
    let env = Env::default();
    let mut reversed = Vec::new(&env);
    reversed.push_back(limit(&env, 0x22, 250, 1_000, 1));
    reversed.push_back(limit(&env, 0x11, 1_000_000, 5_000_000, 10));
    let p = policy(&env, reversed, None, 1_800_000_000);

    let (_, expected) = vector("unsorted-tokens");
    assert_eq!(hex(&fingerprint::fingerprint(&env, &p).unwrap()), expected);
    // ...which is the same policy as the forward one, on both chains.
    let (_, forward) = vector("every-ad");
    assert_eq!(expected, forward);
}

#[test]
fn a_scoped_agent_sorts_its_ads() {
    let env = Env::default();
    let mut limits = Vec::new(&env);
    limits.push_back(limit(&env, 0x11, 7, 7, 1));
    let mut ads = Vec::new(&env);
    // deliberately the wrong way round: the encoder sorts, the owner does not have to
    ads.push_back(String::from_str(&env, "ad-zulu"));
    ads.push_back(String::from_str(&env, "ad-alpha"));
    let p = policy(&env, limits, Some(ads), 0);

    let (encoded, expected) = vector("scoped");
    assert_eq!(encoded_hex(&env, &p), encoded);
    assert_eq!(hex(&fingerprint::fingerprint(&env, &p).unwrap()), expected);
}

#[test]
fn the_widest_limit_this_chain_can_hold() {
    let env = Env::default();
    let mut limits = Vec::new(&env);
    limits.push_back(limit(&env, 0x11, u128::MAX, u128::MAX, u128::MAX));
    let p = policy(&env, limits, None, u64::MAX);

    let (encoded, expected) = vector("u128-ceiling");
    assert_eq!(encoded_hex(&env, &p), encoded);
    assert_eq!(hex(&fingerprint::fingerprint(&env, &p).unwrap()), expected);
}

#[test]
fn revoking_does_not_change_the_fingerprint() {
    // Revoking is overwriting the fingerprint on the EVM side, so the flag has no place in the
    // bytes; if it were in them, a revoked policy would hash differently and the two chains would
    // disagree about what "the same policy" means.
    let env = Env::default();
    let mut limits = Vec::new(&env);
    limits.push_back(limit(&env, 0x11, 7, 7, 1));
    let live = policy(&env, limits, None, 0);
    let mut revoked = live.clone();
    revoked.revoked = true;
    assert_eq!(
        fingerprint::fingerprint(&env, &live).unwrap(),
        fingerprint::fingerprint(&env, &revoked).unwrap()
    );
}

#[test]
fn live_buckets_are_not_part_of_the_policy() {
    let env = Env::default();
    let mut limits = Vec::new(&env);
    limits.push_back(limit(&env, 0x11, 7, 7, 1));
    let fresh = policy(&env, limits, None, 0);
    let mut spent = fresh.clone();
    let mut buckets = Vec::new(&env);
    buckets.push_back(crate::policy::TokenBucket {
        token: bytes32(&env, 0x11),
        bucket: Bucket { level: 3, last_ts: 99 },
    });
    spent.buckets = buckets;
    assert_eq!(
        fingerprint::fingerprint(&env, &fresh).unwrap(),
        fingerprint::fingerprint(&env, &spent).unwrap(),
        "a policy would otherwise need a new fingerprint after every trade"
    );
}
