//! ProofBridge Stellar integration tests
//!
//! Tests the full contract flow: deploy all 4 contracts, create ads, lock
//! orders, and unlock with ZK proofs — going through the ad-manager and
//! order-portal contracts exactly as real-world usage would.
//!
//! Fixtures are pre-generated by tests/fixtures/generate_fixtures.ts using
//! deterministic contract addresses so the EIP-712 order hashes match.
//! Proof-derived values (order hash, target root, nullifiers) are read from
//! test_params.json so regenerating fixtures doesn't require code changes.

extern crate std;

use ed25519_dalek::{Signer, SigningKey};
use serde::Deserialize;
use sha3::{Digest, Keccak256};
use soroban_sdk::{
    contract, contractimpl, Address, Bytes, BytesN, Env, MuxedAddress, String as SorobanString,
};
use stellar_strkey::Contract;
use stellar_tokens::fungible::{Base, FungibleToken};

// ---------------------------------------------------------------------------
// WASM blobs
// ---------------------------------------------------------------------------

const VERIFIER_WASM: &[u8] = include_bytes!("../target/wasm32v1-none/release/verifier.wasm");
const MERKLE_WASM: &[u8] = include_bytes!("../target/wasm32v1-none/release/merkle_manager.wasm");
const AD_MANAGER_WASM: &[u8] = include_bytes!("../target/wasm32v1-none/release/ad_manager.wasm");
const ORDER_PORTAL_WASM: &[u8] =
    include_bytes!("../target/wasm32v1-none/release/order_portal.wasm");

// ---------------------------------------------------------------------------
// Inline SAC-convention token contract (stellar-tokens)
// ---------------------------------------------------------------------------

#[contract]
pub struct TokenContract;

#[contractimpl]
impl TokenContract {
    pub fn __constructor(
        e: &Env,
        owner: Address,
        initial_supply: i128,
        decimals: u32,
        name: SorobanString,
        symbol: SorobanString,
    ) {
        Base::set_metadata(e, decimals, name, symbol);
        Base::mint(e, &owner, initial_supply);
    }

    pub fn mint(e: &Env, to: Address, amount: i128) {
        Base::mint(e, &to, amount);
    }

    pub fn set_fail_transfers(e: &Env, fail: bool) {
        e.storage()
            .instance()
            .set(&soroban_sdk::symbol_short!("fail"), &fail);
    }
}

#[contractimpl(contracttrait)]
impl FungibleToken for TokenContract {
    type ContractType = Base;

    fn transfer(e: &Env, from: Address, to: soroban_sdk::MuxedAddress, amount: i128) {
        let fail: bool = e
            .storage()
            .instance()
            .get(&soroban_sdk::symbol_short!("fail"))
            .unwrap_or(false);
        if fail {
            panic!("transfers disabled");
        }
        Base::transfer(e, &from, &to, amount);
    }
}

// ---------------------------------------------------------------------------
// Contract imports (typed Client wrappers)
// ---------------------------------------------------------------------------

mod verifier_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/verifier.wasm");
}

mod merkle_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/merkle_manager.wasm");
}

mod ad_manager_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/ad_manager.wasm");
}

mod order_portal_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/order_portal.wasm");
}

// ---------------------------------------------------------------------------
// Proof fixtures (binary, generated by tests/fixtures/generate_fixtures.ts)
// ---------------------------------------------------------------------------

const VK: &[u8] = include_bytes!("fixtures/vk");
const PROOF_BRIDGER: &[u8] = include_bytes!("fixtures/proof_bridger.bin");
const PROOF_AD_CREATOR: &[u8] = include_bytes!("fixtures/proof_ad_creator.bin");

// ---------------------------------------------------------------------------
// Test parameters loaded from JSON (generated by generate_fixtures.ts)
// ---------------------------------------------------------------------------

const TEST_PARAMS_JSON: &str = include_str!("fixtures/test_params.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
struct TestParamsJson {
    secret: String,
    order_hash: String,
    order_hash_mod: String,
    ad_root: String,
    order_root: String,
    bridger_nullifier: String,
    ad_creator_nullifier: String,
    element_index: u64,
    width: u64,
    contract_addresses: ContractAddressesJson,
    order_params: OrderParamsJson,
    chain_ids: ChainIdsJson,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ContractAddressesJson {
    ad_manager: String,
    order_portal: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
struct OrderParamsJson {
    order_chain_token: String,
    ad_chain_token: String,
    amount: String,
    bridger: String,
    order_chain_id: String,
    order_portal: String,
    order_recipient: String,
    ad_chain_id: String,
    ad_manager: String,
    ad_id: String,
    ad_creator: String,
    ad_recipient: String,
    salt: String,
    order_decimals: u32,
    ad_decimals: u32,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ChainIdsJson {
    order_chain_id: u128,
    ad_chain_id: u128,
}

/// Parsed test parameters with raw byte arrays ready for use.
struct TestParams {
    order_hash: [u8; 32],
    ad_root: [u8; 32],
    order_root: [u8; 32],
    bridger_nullifier: [u8; 32],
    ad_creator_nullifier: [u8; 32],
    // Contract addresses
    ad_manager_id: [u8; 32],
    order_portal_id: [u8; 32],
    // Order fields
    order_chain_token: [u8; 32],
    ad_chain_token: [u8; 32],
    amount: u128,
    bridger: [u8; 32],
    order_recipient: [u8; 32],
    ad_creator: [u8; 32],
    ad_recipient: [u8; 32],
    salt: u128,
    ad_id: std::string::String,
    order_decimals: u32,
    ad_decimals: u32,
    // Chain IDs
    order_chain_id: u128,
    ad_chain_id: u128,
}

fn hex_to_array(hex_str: &str) -> [u8; 32] {
    let clean = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    let mut arr = [0u8; 32];
    hex::decode_to_slice(clean, &mut arr).unwrap();
    arr
}

/// Decode a Stellar strkey address (C... or G...) to its 32-byte payload
fn strkey_to_array(strkey: &str) -> [u8; 32] {
    if strkey.starts_with('C') {
        stellar_strkey::Contract::from_string(strkey)
            .expect("invalid C... address")
            .0
    } else if strkey.starts_with('G') {
        stellar_strkey::ed25519::PublicKey::from_string(strkey)
            .expect("invalid G... address")
            .0
    } else {
        panic!("Unknown strkey prefix: {}", strkey);
    }
}

fn load_test_params() -> TestParams {
    let json: TestParamsJson = serde_json::from_str(TEST_PARAMS_JSON).unwrap();
    TestParams {
        // These remain 0x hex (proof-derived values)
        order_hash: hex_to_array(&json.order_hash),
        ad_root: hex_to_array(&json.ad_root),
        order_root: hex_to_array(&json.order_root),
        bridger_nullifier: hex_to_array(&json.bridger_nullifier),
        ad_creator_nullifier: hex_to_array(&json.ad_creator_nullifier),
        // Contract addresses (C... strkey format)
        ad_manager_id: strkey_to_array(&json.contract_addresses.ad_manager),
        order_portal_id: strkey_to_array(&json.contract_addresses.order_portal),
        // Token addresses (C... strkey format)
        order_chain_token: strkey_to_array(&json.order_params.order_chain_token),
        ad_chain_token: strkey_to_array(&json.order_params.ad_chain_token),
        amount: json.order_params.amount.parse().unwrap(),
        // User addresses (G... strkey format)
        bridger: strkey_to_array(&json.order_params.bridger),
        order_recipient: strkey_to_array(&json.order_params.order_recipient),
        ad_creator: strkey_to_array(&json.order_params.ad_creator),
        ad_recipient: strkey_to_array(&json.order_params.ad_recipient),
        salt: json.order_params.salt.parse().unwrap(),
        ad_id: json.order_params.ad_id,
        order_decimals: json.order_params.order_decimals,
        ad_decimals: json.order_params.ad_decimals,
        order_chain_id: json.chain_ids.order_chain_id,
        ad_chain_id: json.chain_ids.ad_chain_id,
    }
}

// ---------------------------------------------------------------------------
// Keccak256 + request hash helpers (mirrors proofbridge-core/src/auth.rs)
// ---------------------------------------------------------------------------

fn keccak256(data: &[u8]) -> [u8; 32] {
    let mut hasher = Keccak256::new();
    hasher.update(data);
    hasher.finalize().into()
}

/// Replicate proofbridge_core::auth::hash_string_field
fn hash_string_field(s: &str) -> [u8; 32] {
    keccak256(s.as_bytes())
}

/// Replicate proofbridge_core::auth::hash_request
fn hash_request(
    auth_token: &[u8; 32],
    time_to_expire: u64,
    action: &str,
    params: &[u8],
    chain_id: u128,
    contract_address: &[u8; 32],
) -> [u8; 32] {
    let mut buf = [0u8; 512];
    let mut offset = 0;

    buf[offset..offset + 32].copy_from_slice(auth_token);
    offset += 32;

    buf[offset..offset + 8].copy_from_slice(&time_to_expire.to_be_bytes());
    offset += 8;

    let action_hash = keccak256(action.as_bytes());
    buf[offset..offset + 32].copy_from_slice(&action_hash);
    offset += 32;

    buf[offset..offset + params.len()].copy_from_slice(params);
    offset += params.len();

    buf[offset..offset + 16].copy_from_slice(&chain_id.to_be_bytes());
    offset += 16;

    buf[offset..offset + 32].copy_from_slice(contract_address);
    offset += 32;

    keccak256(&buf[..offset])
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn bytes32_to_bytesn(env: &Env, arr: &[u8; 32]) -> BytesN<32> {
    BytesN::from_array(env, arr)
}

/// Create an Address from a 32-byte contract ID
fn contract_address(env: &Env, id: &[u8; 32]) -> Address {
    let strkey = Contract(*id).to_string();
    let soroban_str = SorobanString::from_str(env, &strkey);
    Address::from_string(&soroban_str)
}

/// Generate an ed25519 keypair and derive the Stellar account address
fn generate_signer(env: &Env) -> (SigningKey, BytesN<32>, Address) {
    let mut rng = rand::thread_rng();
    let signing_key = SigningKey::generate(&mut rng);
    let pubkey_bytes = signing_key.verifying_key().to_bytes();
    let pub_bytes32 = BytesN::from_array(env, &pubkey_bytes);

    let strkey = stellar_strkey::ed25519::PublicKey(pubkey_bytes).to_string();
    let soroban_str = SorobanString::from_str(env, &strkey);
    let address = Address::from_string(&soroban_str);

    (signing_key, pub_bytes32, address)
}

/// Sign a 32-byte message hash with ed25519, returning a BytesN<64> signature
fn ed25519_sign(env: &Env, signing_key: &SigningKey, message_hash: &[u8; 32]) -> BytesN<64> {
    let sig = signing_key.sign(message_hash);
    BytesN::from_array(env, &sig.to_bytes())
}

/// Counter for unique auth tokens
struct AuthTokenCounter(u8);

impl AuthTokenCounter {
    fn new() -> Self {
        Self(1)
    }

    fn next(&mut self) -> [u8; 32] {
        let mut token = [0u8; 32];
        token[0] = self.0;
        self.0 += 1;
        token
    }
}

// ---------------------------------------------------------------------------
// Test setup
// ---------------------------------------------------------------------------

#[allow(dead_code)]
struct TestSetup<'a> {
    env: Env,
    // Fixture params (loaded from test_params.json)
    tp: TestParams,
    // Contracts
    ad_manager: ad_manager_contract::Client<'a>,
    order_portal: order_portal_contract::Client<'a>,
    // Admin signer
    signing_key: SigningKey,
    admin_pubkey: BytesN<32>,
    admin_addr: Address,
    // Token addresses (deployed test-token contracts)
    ad_token_addr: Address,
    order_token_addr: Address,
    // Auth token counter (each call needs unique token)
    auth_counter: AuthTokenCounter,
}

impl<'a> TestSetup<'a> {
    /// Sign a request for the ad-manager (computes hash then signs)
    fn sign_ad_manager_request(
        &mut self,
        action: &str,
        params: &[u8],
    ) -> (BytesN<64>, BytesN<32>, u64) {
        let auth_token = self.auth_counter.next();
        let time_to_expire = u64::MAX;

        let message_hash = hash_request(
            &auth_token,
            time_to_expire,
            action,
            params,
            self.tp.ad_chain_id,
            &self.tp.ad_manager_id,
        );

        let signature = ed25519_sign(&self.env, &self.signing_key, &message_hash);
        let auth_token_bn = BytesN::from_array(&self.env, &auth_token);

        (signature, auth_token_bn, time_to_expire)
    }

    /// Sign a request for the order-portal
    fn sign_order_portal_request(
        &mut self,
        action: &str,
        params: &[u8],
    ) -> (BytesN<64>, BytesN<32>, u64) {
        let auth_token = self.auth_counter.next();
        let time_to_expire = u64::MAX;

        let message_hash = hash_request(
            &auth_token,
            time_to_expire,
            action,
            params,
            self.tp.order_chain_id,
            &self.tp.order_portal_id,
        );

        let signature = ed25519_sign(&self.env, &self.signing_key, &message_hash);
        let auth_token_bn = BytesN::from_array(&self.env, &auth_token);

        (signature, auth_token_bn, time_to_expire)
    }
}

fn setup() -> TestSetup<'static> {
    let tp = load_test_params();

    let env = Env::default();
    env.mock_all_auths_allowing_non_root_auth();
    env.cost_estimate().budget().reset_unlimited();

    let mut auth_counter = AuthTokenCounter::new();

    // Generate admin keypair
    let (signing_key, admin_pubkey, admin_addr) = generate_signer(&env);

    // Deploy verifiers
    let vk_bytes = Bytes::from_slice(&env, VK);
    let ad_verifier_id = env.register(VERIFIER_WASM, (vk_bytes.clone(),));
    let order_verifier_id = env.register(VERIFIER_WASM, (vk_bytes,));

    // Deploy merkle managers
    let ad_merkle_id = env.register(MERKLE_WASM, ());
    let ad_merkle = merkle_contract::Client::new(&env, &ad_merkle_id);
    ad_merkle.initialize(&admin_addr);

    let order_merkle_id = env.register(MERKLE_WASM, ());
    let order_merkle = merkle_contract::Client::new(&env, &order_merkle_id);
    order_merkle.initialize(&admin_addr);

    // Deploy ad-manager at deterministic address
    let ad_manager_addr = contract_address(&env, &tp.ad_manager_id);
    env.register_at(&ad_manager_addr, AD_MANAGER_WASM, ());
    let ad_manager = ad_manager_contract::Client::new(&env, &ad_manager_addr);

    // Deploy order-portal at deterministic address
    let order_portal_addr = contract_address(&env, &tp.order_portal_id);
    env.register_at(&order_portal_addr, ORDER_PORTAL_WASM, ());
    let order_portal = order_portal_contract::Client::new(&env, &order_portal_addr);

    // Deploy SAC-convention tokens at deterministic addresses matching fixture params.
    // Both contracts resolve BytesN<32> → Contract address → token::Client
    let token_name = SorobanString::from_str(&env, "TestToken");
    let token_symbol = SorobanString::from_str(&env, "TT");
    let ad_token_addr = contract_address(&env, &tp.ad_chain_token);
    env.register_at(
        &ad_token_addr,
        TokenContract,
        (
            admin_addr.clone(),
            0i128,
            tp.ad_decimals,
            token_name.clone(),
            token_symbol.clone(),
        ),
    );

    let order_token_addr = contract_address(&env, &tp.order_chain_token);
    env.register_at(
        &order_token_addr,
        TokenContract,
        (
            admin_addr.clone(),
            0i128,
            tp.order_decimals,
            token_name.clone(),
            token_symbol.clone(),
        ),
    );

    // w_native_token is required by the constructor but not used for non-native tokens
    let w_native_token = ad_token_addr.clone();

    // Initialize contracts (uses require_auth, mocked)
    ad_manager.initialize(
        &admin_addr,
        &ad_verifier_id,
        &ad_merkle_id,
        &w_native_token,
        &tp.ad_chain_id,
    );
    order_portal.initialize(
        &admin_addr,
        &order_verifier_id,
        &order_merkle_id,
        &order_token_addr,
        &tp.order_chain_id,
    );

    // Set merkle managers
    ad_merkle.set_manager(&ad_manager_addr, &true);
    order_merkle.set_manager(&order_portal_addr, &true);

    // --- Ad-manager: set_chain (uses require_auth, mocked) ---
    ad_manager.set_chain(
        &tp.order_chain_id,
        &bytes32_to_bytesn(&env, &tp.order_portal_id),
        &true,
    );

    // --- Order-portal: set_chain (uses require_auth, mocked) ---
    order_portal.set_chain(
        &tp.ad_chain_id,
        &bytes32_to_bytesn(&env, &tp.ad_manager_id),
        &true,
    );

    // --- Ad-manager: set_token_route (uses require_auth, mocked) ---
    ad_manager.set_token_route(
        &bytes32_to_bytesn(&env, &tp.ad_chain_token),
        &bytes32_to_bytesn(&env, &tp.order_chain_token),
        &tp.order_chain_id,
    );

    // --- Order-portal: set_token_route (uses require_auth, mocked) ---
    order_portal.set_token_route(
        &bytes32_to_bytesn(&env, &tp.order_chain_token),
        &tp.ad_chain_id,
        &bytes32_to_bytesn(&env, &tp.ad_chain_token),
    );

    // Mint tokens to admin via the SAC-convention token
    let ad_token_client = TokenContractClient::new(&env, &ad_token_addr);
    ad_token_client.mint(&admin_addr, &(tp.amount as i128 * 10));

    // --- Ad-manager: create_ad (ed25519 signed) ---
    {
        let auth_token = auth_counter.next();
        let time_to_expire = u64::MAX;

        // params: ad_id_hash(32) + ad_token(32) + initial_amount(16) + order_chain_id(16) + ad_recipient(32) = 128
        let mut params = [0u8; 128];
        let ad_id_hash = hash_string_field(&tp.ad_id);
        params[0..32].copy_from_slice(&ad_id_hash);
        params[32..64].copy_from_slice(&tp.ad_chain_token);
        params[64..80].copy_from_slice(&tp.amount.to_be_bytes());
        params[80..96].copy_from_slice(&tp.order_chain_id.to_be_bytes());
        params[96..128].copy_from_slice(&tp.ad_recipient);

        let message_hash = hash_request(
            &auth_token,
            time_to_expire,
            "createAd",
            &params,
            tp.ad_chain_id,
            &tp.ad_manager_id,
        );
        let signature = ed25519_sign(&env, &signing_key, &message_hash);
        let auth_token_bn = BytesN::from_array(&env, &auth_token);

        ad_manager.create_ad(
            &signature,
            &admin_pubkey,
            &auth_token_bn,
            &time_to_expire,
            &admin_addr,
            &SorobanString::from_str(&env, &tp.ad_id),
            &bytes32_to_bytesn(&env, &tp.ad_chain_token),
            &tp.amount,
            &tp.order_chain_id,
            &bytes32_to_bytesn(&env, &tp.ad_recipient),
        );
    }

    TestSetup {
        env,
        tp,
        ad_manager,
        order_portal,
        signing_key,
        admin_pubkey,
        admin_addr,
        ad_token_addr,
        order_token_addr,
        auth_counter,
    }
}

// ===========================================================================
// Helper: build request hash params for various actions
// ===========================================================================

fn lock_for_order_params(ad_id: &str, order_hash: &[u8; 32]) -> [u8; 64] {
    let mut params = [0u8; 64];
    params[0..32].copy_from_slice(&hash_string_field(ad_id));
    params[32..64].copy_from_slice(order_hash);
    params
}

fn unlock_order_params(ad_id: &str, order_hash: &[u8; 32], target_root: &[u8; 32]) -> [u8; 96] {
    let mut params = [0u8; 96];
    params[0..32].copy_from_slice(&hash_string_field(ad_id));
    params[32..64].copy_from_slice(order_hash);
    params[64..96].copy_from_slice(target_root);
    params
}

fn create_order_params(ad_id: &str, order_hash: &[u8; 32]) -> [u8; 64] {
    let mut params = [0u8; 64];
    params[0..32].copy_from_slice(&hash_string_field(ad_id));
    params[32..64].copy_from_slice(order_hash);
    params
}

// ===========================================================================
// Helpers: build contract OrderParams from TestParams
// ===========================================================================

fn ad_manager_order_params(env: &Env, tp: &TestParams) -> ad_manager_contract::OrderParams {
    ad_manager_contract::OrderParams {
        order_chain_token: bytes32_to_bytesn(env, &tp.order_chain_token),
        ad_chain_token: bytes32_to_bytesn(env, &tp.ad_chain_token),
        amount: tp.amount,
        bridger: bytes32_to_bytesn(env, &tp.bridger),
        order_chain_id: tp.order_chain_id,
        src_order_portal: bytes32_to_bytesn(env, &tp.order_portal_id),
        order_recipient: bytes32_to_bytesn(env, &tp.order_recipient),
        ad_id: SorobanString::from_str(env, &tp.ad_id),
        ad_creator: bytes32_to_bytesn(env, &tp.ad_creator),
        ad_recipient: bytes32_to_bytesn(env, &tp.ad_recipient),
        salt: tp.salt,
        order_decimals: tp.order_decimals,
        ad_decimals: tp.ad_decimals,
    }
}

fn order_portal_order_params(env: &Env, tp: &TestParams) -> order_portal_contract::OrderParams {
    order_portal_contract::OrderParams {
        order_chain_token: bytes32_to_bytesn(env, &tp.order_chain_token),
        ad_chain_token: bytes32_to_bytesn(env, &tp.ad_chain_token),
        amount: tp.amount,
        bridger: bytes32_to_bytesn(env, &tp.bridger),
        order_recipient: bytes32_to_bytesn(env, &tp.order_recipient),
        ad_chain_id: tp.ad_chain_id,
        ad_manager: bytes32_to_bytesn(env, &tp.ad_manager_id),
        ad_id: SorobanString::from_str(env, &tp.ad_id),
        ad_creator: bytes32_to_bytesn(env, &tp.ad_creator),
        ad_recipient: bytes32_to_bytesn(env, &tp.ad_recipient),
        salt: tp.salt,
        order_decimals: tp.order_decimals,
        ad_decimals: tp.ad_decimals,
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[test]
fn test_ad_manager_lock_for_order() {
    let mut s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    // Sign lockForOrder
    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (signature, auth_token, time_to_expire) =
        s.sign_ad_manager_request("lockForOrder", &lock_params);

    let order_hash = s.ad_manager.lock_for_order(
        &signature,
        &s.admin_pubkey,
        &auth_token,
        &time_to_expire,
        &params,
    );

    // Verify the order hash matches fixture
    assert_eq!(
        order_hash,
        bytes32_to_bytesn(&s.env, &s.tp.order_hash),
        "Ad-manager order hash must match fixture"
    );

    // Ad-manager appends side 0 ⇒ its own root is the ad-chain root.
    let root = s.ad_manager.get_latest_merkle_root();
    assert_eq!(
        root,
        bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        "Ad-manager merkle root must match ad_root"
    );

    // Verify order status is Open
    assert_eq!(
        s.ad_manager.get_order_status(&order_hash),
        ad_manager_contract::Status::Open,
    );
}

#[test]
fn test_ad_manager_unlock_with_bridger_proof() {
    let mut s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    // Lock first
    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_ad_manager_request("lockForOrder", &lock_params);
    s.ad_manager
        .lock_for_order(&sig, &s.admin_pubkey, &tok, &exp, &params);

    // Bridger proves inclusion in the counterparty (order-chain) root.
    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.order_root);
    let (sig, tok, exp) = s.sign_ad_manager_request("unlockOrder", &unlock_params);

    s.ad_manager.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.order_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );

    // Verify order is now Filled
    let order_hash = bytes32_to_bytesn(&s.env, &s.tp.order_hash);
    assert_eq!(
        s.ad_manager.get_order_status(&order_hash),
        ad_manager_contract::Status::Filled,
    );
}

#[test]
fn test_order_portal_create_and_unlock() {
    let mut s = setup();

    // Mint tokens to bridger
    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let order_token_client = TokenContractClient::new(&s.env, &s.order_token_addr);
    order_token_client.mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let params = order_portal_order_params(&s.env, &s.tp);

    // Sign createOrder
    let create_params = create_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_order_portal_request("createOrder", &create_params);

    let order_hash = s
        .order_portal
        .create_order(&sig, &s.admin_pubkey, &tok, &exp, &params);

    assert_eq!(
        order_hash,
        bytes32_to_bytesn(&s.env, &s.tp.order_hash),
        "Order-portal order hash must match fixture"
    );
    assert_eq!(
        s.order_portal.get_order_status(&order_hash),
        order_portal_contract::Status::Open,
    );

    // Ad-creator proves inclusion in the counterparty (ad-chain) root.
    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.ad_root);
    let (sig, tok, exp) = s.sign_order_portal_request("unlockOrder", &unlock_params);

    s.order_portal.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    );

    assert_eq!(
        s.order_portal.get_order_status(&order_hash),
        order_portal_contract::Status::Filled,
    );
}

#[test]
fn test_full_cross_chain_flow() {
    let mut s = setup();

    // ----- AD CHAIN: lock order -----
    let ad_params = ad_manager_order_params(&s.env, &s.tp);

    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_ad_manager_request("lockForOrder", &lock_params);

    let ad_order_hash = s
        .ad_manager
        .lock_for_order(&sig, &s.admin_pubkey, &tok, &exp, &ad_params);

    // ----- ORDER CHAIN: create order -----
    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let order_token_client = TokenContractClient::new(&s.env, &s.order_token_addr);
    order_token_client.mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let order_params = order_portal_order_params(&s.env, &s.tp);

    let create_params = create_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_order_portal_request("createOrder", &create_params);

    let order_hash = s
        .order_portal
        .create_order(&sig, &s.admin_pubkey, &tok, &exp, &order_params);

    // Both chains compute the same order hash
    assert_eq!(
        ad_order_hash, order_hash,
        "Order hash must be identical on both chains"
    );

    // ----- AD CHAIN: bridger unlocks proving the order-chain (counterparty) root -----
    let bridger_target_root = s.order_portal.get_latest_merkle_root();
    let bridger_target_root_arr = bridger_target_root.to_array();
    let unlock_params =
        unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &bridger_target_root_arr);
    let (sig, tok, exp) = s.sign_ad_manager_request("unlockOrder", &unlock_params);

    s.ad_manager.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &ad_params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bridger_target_root,
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );

    assert_eq!(
        s.ad_manager.get_order_status(&order_hash),
        ad_manager_contract::Status::Filled,
    );

    // ----- ORDER CHAIN: ad creator unlocks proving the ad-chain (counterparty) root -----
    let adcreator_target_root = s.ad_manager.get_latest_merkle_root();
    let adcreator_target_root_arr = adcreator_target_root.to_array();
    let unlock_params =
        unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &adcreator_target_root_arr);
    let (sig, tok, exp) = s.sign_order_portal_request("unlockOrder", &unlock_params);

    s.order_portal.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &order_params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &adcreator_target_root,
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    );

    assert_eq!(
        s.order_portal.get_order_status(&order_hash),
        order_portal_contract::Status::Filled,
    );
}

#[test]
fn test_nullifier_prevents_double_unlock() {
    let mut s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    // Lock
    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_ad_manager_request("lockForOrder", &lock_params);
    s.ad_manager
        .lock_for_order(&sig, &s.admin_pubkey, &tok, &exp, &params);

    // First unlock succeeds (bridger proves the order-chain root)
    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.order_root);
    let (sig, tok, exp) = s.sign_ad_manager_request("unlockOrder", &unlock_params);

    s.ad_manager.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.order_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );

    // Second unlock should fail (order already filled)
    let unlock_params2 = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.order_root);
    let (sig2, tok2, exp2) = s.sign_ad_manager_request("unlockOrder", &unlock_params2);

    let result = s.ad_manager.try_unlock(
        &sig2,
        &s.admin_pubkey,
        &tok2,
        &exp2,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.order_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );

    assert!(result.is_err(), "Double unlock must fail");
}

// ============================================================================
// Gate 2 — root-verification module wiring (1.2c)
// ============================================================================

mod counterparty_verifier_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/counterparty_verifier.wasm");
}

mod bls_key_registry_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/bls_key_registry.wasm");
}

#[soroban_sdk::contract]
pub struct MockRootVerifier;

#[soroban_sdk::contractimpl]
impl MockRootVerifier {
    pub fn set_ok(env: Env, ok: bool) {
        env.storage()
            .instance()
            .set(&soroban_sdk::symbol_short!("ok"), &ok);
    }

    pub fn is_root_valid(
        env: Env,
        _source_chain_id: u128,
        _root: BytesN<32>,
        _metadata: Bytes,
    ) -> bool {
        env.storage()
            .instance()
            .get(&soroban_sdk::symbol_short!("ok"))
            .unwrap_or(false)
    }
}

fn locked_ad_order(s: &mut TestSetup) -> ad_manager_contract::OrderParams {
    let params = ad_manager_order_params(&s.env, &s.tp);
    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_ad_manager_request("lockForOrder", &lock_params);
    s.ad_manager
        .lock_for_order(&sig, &s.admin_pubkey, &tok, &exp, &params);
    params
}

fn ad_unlock(s: &mut TestSetup, params: &ad_manager_contract::OrderParams, cosig: &Bytes) -> bool {
    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.order_root);
    let (sig, tok, exp) = s.sign_ad_manager_request("unlockOrder", &unlock_params);
    s.ad_manager
        .try_unlock(
            &sig,
            &s.admin_pubkey,
            &tok,
            &exp,
            params,
            &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
            &bytes32_to_bytesn(&s.env, &s.tp.order_root),
            &Bytes::from_slice(&s.env, PROOF_BRIDGER),
            cosig,
        )
        .is_ok()
}

#[test]
fn test_gate2_mock_true_unlocks_and_clears_in_flight() {
    let mut s = setup();
    let params = locked_ad_order(&mut s);

    let mock = s.env.register(MockRootVerifier, ());
    MockRootVerifierClient::new(&s.env, &mock).set_ok(&true);
    s.ad_manager.set_root_verifier(&s.tp.order_chain_id, &mock);

    assert!(s.ad_manager.has_open_positions(&params.ad_creator));
    assert!(s.ad_manager.has_open_positions(&params.bridger));

    let empty = Bytes::new(&s.env);
    assert!(ad_unlock(&mut s, &params, &empty));

    assert!(!s.ad_manager.has_open_positions(&params.ad_creator));
    assert!(!s.ad_manager.has_open_positions(&params.bridger));
}

#[test]
fn test_gate2_mock_false_blocks_unlock() {
    let mut s = setup();
    let params = locked_ad_order(&mut s);

    let mock = s.env.register(MockRootVerifier, ());
    MockRootVerifierClient::new(&s.env, &mock).set_ok(&false);
    s.ad_manager.set_root_verifier(&s.tp.order_chain_id, &mock);

    let empty = Bytes::new(&s.env);
    assert!(!ad_unlock(&mut s, &params, &empty));
}

#[test]
fn test_gate2_real_module_rejects_root_outside_signed_auth() {
    let mut s = setup();
    let params = locked_ad_order(&mut s);

    // Real module C wired to a dummy registry: the fixture's target root is
    // not inside the vector SettlementAuth, so it fails before any lookup.
    let module = s.env.register(counterparty_verifier_contract::WASM, ());
    counterparty_verifier_contract::Client::new(&s.env, &module).initialize(&s.ad_manager.address);
    s.ad_manager
        .set_root_verifier(&s.tp.order_chain_id, &module);

    let vectors: serde_json::Value =
        serde_json::from_str(include_str!("../../test-vectors/bls-encodings.json")).unwrap();
    let hexv =
        |v: &serde_json::Value| hex::decode(v.as_str().unwrap().trim_start_matches("0x")).unwrap();
    let auth = &vectors["settlement"]["auth"];
    let mut cosig = std::vec![1u8];
    let ocid: u128 = auth["orderChainId"].as_str().unwrap().parse().unwrap();
    let acid: u128 = auth["adChainId"].as_str().unwrap().parse().unwrap();
    cosig.extend_from_slice(&ocid.to_be_bytes());
    cosig.extend_from_slice(&acid.to_be_bytes());
    cosig.extend_from_slice(&hexv(&auth["orderHash"]));
    cosig.extend_from_slice(&hexv(&auth["orderChainRoot"]));
    cosig.extend_from_slice(&hexv(&auth["adChainRoot"]));
    cosig.extend_from_slice(&hexv(&vectors["keys"]["makerBls"]["pk"]["uncompressed"]));
    cosig.extend_from_slice(&hexv(&vectors["keys"]["bridgerBls"]["pk"]["uncompressed"]));
    cosig.extend_from_slice(&hexv(&vectors["settlement"]["aggSig"]["uncompressed"]));

    let cosig_bytes = Bytes::from_slice(&s.env, &cosig);
    assert!(!ad_unlock(&mut s, &params, &cosig_bytes));
}

#[test]
fn test_gate2_garbage_cosig_blocks_unlock() {
    let mut s = setup();
    let params = locked_ad_order(&mut s);

    let module = s.env.register(counterparty_verifier_contract::WASM, ());
    counterparty_verifier_contract::Client::new(&s.env, &module).initialize(&s.ad_manager.address);
    s.ad_manager
        .set_root_verifier(&s.tp.order_chain_id, &module);

    let garbage = Bytes::from_slice(&s.env, &[0xde, 0xad]);
    assert!(!ad_unlock(&mut s, &params, &garbage));
}

#[test]
fn test_gate2_portal_mock_false_blocks_unlock() {
    let mut s = setup();

    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    TokenContractClient::new(&s.env, &s.order_token_addr)
        .mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let params = order_portal_order_params(&s.env, &s.tp);
    let cp = create_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_order_portal_request("createOrder", &cp);
    s.order_portal
        .create_order(&sig, &s.admin_pubkey, &tok, &exp, &params);

    let mock = s.env.register(MockRootVerifier, ());
    MockRootVerifierClient::new(&s.env, &mock).set_ok(&false);
    s.order_portal.set_root_verifier(&s.tp.ad_chain_id, &mock);

    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.ad_root);
    let (sig, tok, exp) = s.sign_order_portal_request("unlockOrder", &unlock_params);
    let res = s.order_portal.try_unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    );
    assert!(res.is_err(), "portal unlock must fail gate 2");
}

// ============================================================================
// Pause + two-step admin (1.2g)
// ============================================================================

#[test]
fn test_pause_blocks_lock_and_unlock_until_unpause() {
    let mut s = setup();

    s.ad_manager.pause();

    let params = ad_manager_order_params(&s.env, &s.tp);
    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_ad_manager_request("lockForOrder", &lock_params);
    let res = s
        .ad_manager
        .try_lock_for_order(&sig, &s.admin_pubkey, &tok, &exp, &params);
    assert!(res.is_err(), "lock must fail while paused");

    s.ad_manager.unpause();
    let (sig, tok, exp) = s.sign_ad_manager_request("lockForOrder", &lock_params);
    s.ad_manager
        .lock_for_order(&sig, &s.admin_pubkey, &tok, &exp, &params);

    s.ad_manager.pause();
    let empty = Bytes::new(&s.env);
    assert!(
        !ad_unlock(&mut s, &params, &empty),
        "unlock must fail while paused"
    );

    s.ad_manager.unpause();
    let empty = Bytes::new(&s.env);
    assert!(ad_unlock(&mut s, &params, &empty));
}

#[test]
fn test_pause_blocks_create_order() {
    let mut s = setup();

    s.order_portal.pause();

    let params = order_portal_order_params(&s.env, &s.tp);
    let cp = create_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_order_portal_request("createOrder", &cp);
    let res = s
        .order_portal
        .try_create_order(&sig, &s.admin_pubkey, &tok, &exp, &params);
    assert!(res.is_err(), "create must fail while paused");
}

#[test]
fn test_two_step_admin_transfer() {
    let s = setup();

    assert!(s.ad_manager.try_accept_admin().is_err());

    use soroban_sdk::testutils::Address as _;
    let next = Address::generate(&s.env);
    s.ad_manager.transfer_admin(&next);
    s.ad_manager.accept_admin();

    s.ad_manager.pause();
    s.ad_manager.unpause();
}

// ============================================================================
// Pull-payment escrow (1.2h)
// ============================================================================

#[test]
fn test_payout_pushes_directly_when_recipient_ok() {
    let mut s = setup();
    let params = locked_ad_order(&mut s);

    let recipient_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.order_recipient).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let token_client = TokenContractClient::new(&s.env, &s.ad_token_addr);
    let before = token_client.balance(&recipient_addr);

    let empty = Bytes::new(&s.env);
    assert!(ad_unlock(&mut s, &params, &empty));

    assert!(
        token_client.balance(&recipient_addr) > before,
        "happy path must pay directly"
    );

    let recipient = bytes32_to_bytesn(&s.env, &s.tp.order_recipient);
    let token = bytes32_to_bytesn(&s.env, &s.tp.ad_chain_token);
    let res = s.ad_manager.try_claim(&recipient, &token);
    assert!(res.is_err(), "nothing to claim after a direct payout");
}

#[test]
fn test_payout_falls_back_to_credit_then_claims_once() {
    let mut s = setup();
    let params = locked_ad_order(&mut s);

    let recipient_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.order_recipient).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let token_client = TokenContractClient::new(&s.env, &s.ad_token_addr);
    let before = token_client.balance(&recipient_addr);

    // recipient's token refuses transfers: unlock must still settle
    token_client.set_fail_transfers(&true);
    let empty = Bytes::new(&s.env);
    assert!(
        ad_unlock(&mut s, &params, &empty),
        "unlock blocked by payout failure"
    );
    assert_eq!(
        token_client.balance(&recipient_addr),
        before,
        "push should have failed"
    );

    let recipient = bytes32_to_bytesn(&s.env, &s.tp.order_recipient);
    let token = bytes32_to_bytesn(&s.env, &s.tp.ad_chain_token);

    // still failing: the credit stays parked
    assert!(s.ad_manager.try_claim(&recipient, &token).is_err());
    assert_eq!(token_client.balance(&recipient_addr), before);

    // token recovers: claim pays exactly once
    token_client.set_fail_transfers(&false);
    s.ad_manager.claim(&recipient, &token);
    assert!(
        token_client.balance(&recipient_addr) > before,
        "claim did not pay"
    );

    let res = s.ad_manager.try_claim(&recipient, &token);
    assert!(res.is_err(), "second claim must fail");
}

#[test]
fn test_portal_payout_pushes_directly() {
    let mut s = setup();

    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    TokenContractClient::new(&s.env, &s.order_token_addr)
        .mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let params = order_portal_order_params(&s.env, &s.tp);
    let cp = create_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_order_portal_request("createOrder", &cp);
    s.order_portal
        .create_order(&sig, &s.admin_pubkey, &tok, &exp, &params);

    let recipient_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.ad_recipient).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let token_client = TokenContractClient::new(&s.env, &s.order_token_addr);
    let before = token_client.balance(&recipient_addr);

    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.ad_root);
    let (sig, tok, exp) = s.sign_order_portal_request("unlockOrder", &unlock_params);
    s.order_portal.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    );

    assert!(
        token_client.balance(&recipient_addr) > before,
        "portal payout must push directly"
    );
    let res = s.order_portal.try_claim(
        &bytes32_to_bytesn(&s.env, &s.tp.ad_recipient),
        &bytes32_to_bytesn(&s.env, &s.tp.order_chain_token),
    );
    assert!(res.is_err(), "nothing to claim after a direct payout");
}

// ============================================================================
// Position guards — the real escrows plug into the registry
// ============================================================================

// Revoke must round-trip through BOTH real escrows cross-contract: a live
// locked trade keeps them busy while an uninvolved account revokes cleanly.
#[test]
fn test_registry_guards_are_the_real_escrows() {
    let mut s = setup();
    let params = locked_ad_order(&mut s);

    let vectors: serde_json::Value =
        serde_json::from_str(include_str!("../../test-vectors/bls-encodings.json")).unwrap();
    let hexv =
        |v: &serde_json::Value| hex::decode(v.as_str().unwrap().trim_start_matches("0x")).unwrap();

    // pin the registry at the contract id the vector PoPs bind
    let regid: [u8; 32] = hexv(&vectors["chains"]["stellarTestnet"]["registryId"])
        .try_into()
        .unwrap();
    let at = Address::from_string(&SorobanString::from_str(
        &s.env,
        &stellar_strkey::Contract(regid).to_string(),
    ));
    let registry = s.env.register_at(&at, bls_key_registry_contract::WASM, ());
    let client = bls_key_registry_contract::Client::new(&s.env, &registry);
    let chain_id: u128 = vectors["chains"]["stellarTestnet"]["chainId"]
        .as_str()
        .unwrap()
        .parse()
        .unwrap();
    client.initialize(&s.admin_addr, &chain_id);

    client.set_position_guards(&soroban_sdk::vec![
        &s.env,
        s.ad_manager.address.clone(),
        s.order_portal.address.clone()
    ]);

    // register the vector maker key (Stellar-home: require_auth, mocked)
    let r = &vectors["registration"]["makerOnStellarTestnet"];
    let account = BytesN::from_array(&s.env, &hexv(&r["account"]).try_into().unwrap());
    let wallet_pk: [u8; 32] = hexv(&vectors["keys"]["makerWallet"]["pk"])
        .try_into()
        .unwrap();
    let owner = Address::from_string(&SorobanString::from_str(
        &s.env,
        &stellar_strkey::ed25519::PublicKey(wallet_pk).to_string(),
    ));
    let pk = BytesN::from_array(&s.env, &hexv(&r["pkNative"]).try_into().unwrap());
    let pop = BytesN::from_array(&s.env, &hexv(&r["pop"]).try_into().unwrap());
    client.register(
        &account,
        &bls_key_registry_contract::OwnerAuth::Stellar(owner.clone()),
        &pk,
        &pop,
        &0,
    );

    // the fixture trade genuinely occupies both guard sources...
    assert!(s.ad_manager.has_open_positions(&params.ad_creator));
    assert!(!s.order_portal.has_open_positions(&account));

    // ...and the revoke round-trips through BOTH real escrows and passes
    client.revoke(
        &account,
        &bls_key_registry_contract::OwnerAuth::Stellar(owner),
        &1,
    );
    assert!(client.try_key_of(&account).is_err());
}
