//! ProofBridge Stellar integration tests
//!
//! Tests the full contract flow: deploy all 4 contracts, create ads, lock
//! orders, and unlock with ZK proofs — going through the ad-manager and
//! order-portal contracts exactly as real-world usage would.
//!
//! Fixtures are pre-generated by tests/fixtures/generate_fixtures.ts using
//! deterministic contract addresses so the EIP-712 order hashes match.
//! Proof-derived values (order hash, target root, nullifiers) are read from
//! test_params.json so regenerating fixtures doesn't require code changes.

extern crate std;

use serde::Deserialize;
use soroban_sdk::{
    contract, contractimpl, testutils::Address as _, Address, Bytes, BytesN, Env,
    String as SorobanString,
};
use stellar_strkey::Contract;
use stellar_tokens::fungible::{Base, FungibleToken};

// ---------------------------------------------------------------------------
// WASM blobs
// ---------------------------------------------------------------------------

const VERIFIER_WASM: &[u8] = include_bytes!("../target/wasm32v1-none/release/verifier.wasm");
const MERKLE_WASM: &[u8] = include_bytes!("../target/wasm32v1-none/release/merkle_manager.wasm");
const AD_MANAGER_WASM: &[u8] = include_bytes!("../target/wasm32v1-none/release/ad_manager.wasm");
const ORDER_PORTAL_WASM: &[u8] =
    include_bytes!("../target/wasm32v1-none/release/order_portal.wasm");

// ---------------------------------------------------------------------------
// Inline SAC-convention token contract (stellar-tokens)
// ---------------------------------------------------------------------------

#[contract]
pub struct TokenContract;

#[contractimpl]
impl TokenContract {
    pub fn __constructor(
        e: &Env,
        owner: Address,
        initial_supply: i128,
        decimals: u32,
        name: SorobanString,
        symbol: SorobanString,
    ) {
        Base::set_metadata(e, decimals, name, symbol);
        Base::mint(e, &owner, initial_supply);
    }

    pub fn mint(e: &Env, to: Address, amount: i128) {
        Base::mint(e, &to, amount);
    }

    pub fn set_fail_transfers(e: &Env, fail: bool) {
        e.storage()
            .instance()
            .set(&soroban_sdk::symbol_short!("fail"), &fail);
    }
}

#[contractimpl(contracttrait)]
impl FungibleToken for TokenContract {
    type ContractType = Base;

    fn transfer(e: &Env, from: Address, to: soroban_sdk::MuxedAddress, amount: i128) {
        let fail: bool = e
            .storage()
            .instance()
            .get(&soroban_sdk::symbol_short!("fail"))
            .unwrap_or(false);
        if fail {
            panic!("transfers disabled");
        }
        Base::transfer(e, &from, &to, amount);
    }
}

// ---------------------------------------------------------------------------
// Contract imports (typed Client wrappers)
// ---------------------------------------------------------------------------

mod verifier_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/verifier.wasm");
}

mod merkle_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/merkle_manager.wasm");
}

mod ad_manager_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/ad_manager.wasm");
}

mod order_portal_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/order_portal.wasm");
}

// ---------------------------------------------------------------------------
// Proof fixtures (binary, generated by tests/fixtures/generate_fixtures.ts)
// ---------------------------------------------------------------------------

const VK: &[u8] = include_bytes!("fixtures/vk");
const PROOF_BRIDGER: &[u8] = include_bytes!("fixtures/proof_bridger.bin");
const PROOF_AD_CREATOR: &[u8] = include_bytes!("fixtures/proof_ad_creator.bin");

// 1.6c compute-cost gate: in-source ceilings for a single WASM unlock (real
// ultrahonk ZK verify) on each escrow. CI builds with `stellar contract build
// --optimize`, so the metered artifact is byte-identical to what the deploy
// flow ships. This gate is ALSO the optimize backstop: an unoptimized unlock meters
// ~109.8M CPU — over the 100M budget below — so a build that silently skipped
// optimization fails right here.
//
// The CPU ceiling is the real Soroban default per-tx CPU budget: a regression that
// pushes unlock over that budget would not submit on-chain, so it MUST fail the
// gate. The metered call uses reset_unlimited() only so the test can *observe* an
// over-budget number instead of aborting mid-call — the assert still enforces it.
//
// Measured optimized baseline (`stellar contract build --optimize`):
//   ad_manager.unlock:   ~96.05M CPU / ~7.21M mem
//   order_portal.unlock: ~95.92M CPU / ~7.16M mem
// ⚠️ Only ~4% CPU headroom under the 100M budget. We deliberately do NOT add the
// usual +10% margin to the CPU ceiling — that would exceed the budget and make the
// gate meaningless. The budget IS the ceiling. Any unlock change that grows CPU has
// almost no room before it stops submitting on-chain; treat a failure here as a
// protocol blocker (shrink the path or raise tx resources), not a number to bump.
const SOROBAN_DEFAULT_TX_CPU_BUDGET: u64 = 100_000_000;
const AD_UNLOCK_CPU_CEILING: u64 = SOROBAN_DEFAULT_TX_CPU_BUDGET;
const AD_UNLOCK_MEM_CEILING: u64 = 8_100_000; // ~7.21M baseline + ~12% headroom
const OP_UNLOCK_CPU_CEILING: u64 = SOROBAN_DEFAULT_TX_CPU_BUDGET;
const OP_UNLOCK_MEM_CEILING: u64 = 8_100_000; // ~7.16M baseline + ~12% headroom

// ---------------------------------------------------------------------------
// Test parameters loaded from JSON (generated by generate_fixtures.ts)
// ---------------------------------------------------------------------------

const TEST_PARAMS_JSON: &str = include_str!("fixtures/test_params.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
struct TestParamsJson {
    secret: String,
    order_hash: String,
    order_hash_mod: String,
    ad_root: String,
    order_root: String,
    bridger_nullifier: String,
    ad_creator_nullifier: String,
    element_index: u64,
    width: u64,
    contract_addresses: ContractAddressesJson,
    order_params: OrderParamsJson,
    chain_ids: ChainIdsJson,
    event_roots: std::collections::BTreeMap<std::string::String, std::string::String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ContractAddressesJson {
    ad_manager: String,
    order_portal: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
struct OrderParamsJson {
    order_chain_token: String,
    ad_chain_token: String,
    amount: String,
    bridger: String,
    order_chain_id: String,
    order_portal: String,
    order_recipient: String,
    ad_chain_id: String,
    ad_manager: String,
    ad_id: String,
    ad_creator: String,
    ad_recipient: String,
    salt: String,
    order_decimals: u32,
    ad_decimals: u32,
    deadline: String,
    ad_settlement_signer: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ChainIdsJson {
    order_chain_id: u128,
    ad_chain_id: u128,
}

/// Parsed test parameters with raw byte arrays ready for use.
struct TestParams {
    order_hash: [u8; 32],
    ad_root: [u8; 32],
    order_root: [u8; 32],
    bridger_nullifier: [u8; 32],
    ad_creator_nullifier: [u8; 32],
    // Contract addresses
    ad_manager_id: [u8; 32],
    order_portal_id: [u8; 32],
    // Order fields
    order_chain_token: [u8; 32],
    ad_chain_token: [u8; 32],
    amount: u128,
    bridger: [u8; 32],
    order_recipient: [u8; 32],
    ad_creator: [u8; 32],
    ad_recipient: [u8; 32],
    salt: u128,
    ad_id: std::string::String,
    order_decimals: u32,
    ad_decimals: u32,
    deadline: u64,
    ad_settlement_signer: [u8; 32],
    // Chain IDs
    order_chain_id: u128,
    ad_chain_id: u128,
    // Event-claim roots for domains 2, 3, 4
    event_roots: [[u8; 32]; 3],
}

fn hex_to_array(hex_str: &str) -> [u8; 32] {
    let clean = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    let mut arr = [0u8; 32];
    hex::decode_to_slice(clean, &mut arr).unwrap();
    arr
}

/// Decode a Stellar strkey address (C... or G...) to its 32-byte payload
fn strkey_to_array(strkey: &str) -> [u8; 32] {
    if strkey.starts_with('C') {
        stellar_strkey::Contract::from_string(strkey)
            .expect("invalid C... address")
            .0
    } else if strkey.starts_with('G') {
        stellar_strkey::ed25519::PublicKey::from_string(strkey)
            .expect("invalid G... address")
            .0
    } else {
        panic!("Unknown strkey prefix: {}", strkey);
    }
}

fn load_test_params() -> TestParams {
    let json: TestParamsJson = serde_json::from_str(TEST_PARAMS_JSON).unwrap();
    TestParams {
        // These remain 0x hex (proof-derived values)
        order_hash: hex_to_array(&json.order_hash),
        ad_root: hex_to_array(&json.ad_root),
        order_root: hex_to_array(&json.order_root),
        bridger_nullifier: hex_to_array(&json.bridger_nullifier),
        ad_creator_nullifier: hex_to_array(&json.ad_creator_nullifier),
        // Contract addresses (C... strkey format)
        ad_manager_id: strkey_to_array(&json.contract_addresses.ad_manager),
        order_portal_id: strkey_to_array(&json.contract_addresses.order_portal),
        // Token addresses (C... strkey format)
        order_chain_token: strkey_to_array(&json.order_params.order_chain_token),
        ad_chain_token: strkey_to_array(&json.order_params.ad_chain_token),
        amount: json.order_params.amount.parse().unwrap(),
        // User addresses (G... strkey format)
        bridger: strkey_to_array(&json.order_params.bridger),
        order_recipient: strkey_to_array(&json.order_params.order_recipient),
        ad_creator: strkey_to_array(&json.order_params.ad_creator),
        ad_recipient: strkey_to_array(&json.order_params.ad_recipient),
        salt: json.order_params.salt.parse().unwrap(),
        ad_id: json.order_params.ad_id,
        order_decimals: json.order_params.order_decimals,
        ad_decimals: json.order_params.ad_decimals,
        deadline: json.order_params.deadline.parse().unwrap(),
        ad_settlement_signer: strkey_to_array(&json.order_params.ad_settlement_signer),
        order_chain_id: json.chain_ids.order_chain_id,
        ad_chain_id: json.chain_ids.ad_chain_id,
        event_roots: [2u32, 3, 4].map(|d| hex_to_array(&json.event_roots[&d.to_string()])),
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn bytes32_to_bytesn(env: &Env, arr: &[u8; 32]) -> BytesN<32> {
    BytesN::from_array(env, arr)
}

/// Create an Address from a 32-byte contract ID
fn contract_address(env: &Env, id: &[u8; 32]) -> Address {
    let strkey = Contract(*id).to_string();
    let soroban_str = SorobanString::from_str(env, &strkey);
    Address::from_string(&soroban_str)
}

// ---------------------------------------------------------------------------
// Test setup
// ---------------------------------------------------------------------------

#[allow(dead_code)]
struct TestSetup<'a> {
    env: Env,
    // Fixture params (loaded from test_params.json)
    tp: TestParams,
    // Contracts
    ad_manager: ad_manager_contract::Client<'a>,
    order_portal: order_portal_contract::Client<'a>,
    // Admin
    admin_addr: Address,
    // Token addresses (deployed test-token contracts)
    ad_token_addr: Address,
    order_token_addr: Address,
}

/// Standard setup: wires a MockRootVerifier that accepts every root on both
/// escrows (the gate is mandatory now — unlock fails without a module).
fn setup() -> TestSetup<'static> {
    setup_with_verifiers(true)
}

fn setup_with_verifiers(wire_root_verifiers: bool) -> TestSetup<'static> {
    let tp = load_test_params();

    let env = Env::default();
    env.mock_all_auths_allowing_non_root_auth();
    env.cost_estimate().budget().reset_unlimited();

    // Generate admin address
    let admin_addr = Address::generate(&env);

    // Deploy verifiers
    let vk_bytes = Bytes::from_slice(&env, VK);
    let ad_verifier_id = env.register(VERIFIER_WASM, (vk_bytes.clone(),));
    let order_verifier_id = env.register(VERIFIER_WASM, (vk_bytes,));

    // Deploy merkle managers
    let ad_merkle_id = env.register(MERKLE_WASM, ());
    let ad_merkle = merkle_contract::Client::new(&env, &ad_merkle_id);
    ad_merkle.initialize(&admin_addr);

    let order_merkle_id = env.register(MERKLE_WASM, ());
    let order_merkle = merkle_contract::Client::new(&env, &order_merkle_id);
    order_merkle.initialize(&admin_addr);

    // Deploy ad-manager at deterministic address
    let ad_manager_addr = contract_address(&env, &tp.ad_manager_id);
    env.register_at(&ad_manager_addr, AD_MANAGER_WASM, ());
    let ad_manager = ad_manager_contract::Client::new(&env, &ad_manager_addr);

    // Deploy order-portal at deterministic address
    let order_portal_addr = contract_address(&env, &tp.order_portal_id);
    env.register_at(&order_portal_addr, ORDER_PORTAL_WASM, ());
    let order_portal = order_portal_contract::Client::new(&env, &order_portal_addr);

    // Deploy SAC-convention tokens at deterministic addresses matching fixture params.
    // Both contracts resolve BytesN<32> → Contract address → token::Client
    let token_name = SorobanString::from_str(&env, "TestToken");
    let token_symbol = SorobanString::from_str(&env, "TT");
    let ad_token_addr = contract_address(&env, &tp.ad_chain_token);
    env.register_at(
        &ad_token_addr,
        TokenContract,
        (
            admin_addr.clone(),
            0i128,
            tp.ad_decimals,
            token_name.clone(),
            token_symbol.clone(),
        ),
    );

    let order_token_addr = contract_address(&env, &tp.order_chain_token);
    env.register_at(
        &order_token_addr,
        TokenContract,
        (
            admin_addr.clone(),
            0i128,
            tp.order_decimals,
            token_name.clone(),
            token_symbol.clone(),
        ),
    );

    // w_native_token is required by the constructor but not used for non-native tokens
    let w_native_token = ad_token_addr.clone();

    // Initialize contracts (uses require_auth, mocked)
    ad_manager.initialize(
        &admin_addr,
        &ad_verifier_id,
        &ad_merkle_id,
        &w_native_token,
        &tp.ad_chain_id,
    );
    order_portal.initialize(
        &admin_addr,
        &order_verifier_id,
        &order_merkle_id,
        &order_token_addr,
        &tp.order_chain_id,
    );

    // Set merkle managers
    ad_merkle.set_manager(&ad_manager_addr, &true);
    order_merkle.set_manager(&order_portal_addr, &true);

    // --- Ad-manager: set_chain (uses require_auth, mocked) ---
    ad_manager.set_chain(
        &tp.order_chain_id,
        &bytes32_to_bytesn(&env, &tp.order_portal_id),
        &true,
    );

    // --- Order-portal: set_chain (uses require_auth, mocked) ---
    order_portal.set_chain(
        &tp.ad_chain_id,
        &bytes32_to_bytesn(&env, &tp.ad_manager_id),
        &true,
    );

    // --- Ad-manager: set_token_route (uses require_auth, mocked) ---
    ad_manager.set_token_route(
        &bytes32_to_bytesn(&env, &tp.ad_chain_token),
        &bytes32_to_bytesn(&env, &tp.order_chain_token),
        &tp.order_chain_id,
    );

    // --- Order-portal: set_token_route (uses require_auth, mocked) ---
    order_portal.set_token_route(
        &bytes32_to_bytesn(&env, &tp.order_chain_token),
        &tp.ad_chain_id,
        &bytes32_to_bytesn(&env, &tp.ad_chain_token),
    );

    // Mint tokens to admin via the SAC-convention token
    let ad_token_client = TokenContractClient::new(&env, &ad_token_addr);
    ad_token_client.mint(&admin_addr, &(tp.amount as i128 * 10));

    // Root-verification gate is mandatory: wire a permissive mock by default.
    if wire_root_verifiers {
        let mock = env.register(MockRootVerifier, ());
        MockRootVerifierClient::new(&env, &mock).set_ok(&true);
        ad_manager.set_root_verifier(&tp.order_chain_id, &mock);
        order_portal.set_root_verifier(&tp.ad_chain_id, &mock);
    }

    // --- Ad-manager: create_ad (creator wallet auth, mocked) ---
    ad_manager.create_ad(
        &admin_addr,
        &SorobanString::from_str(&env, &tp.ad_id),
        &bytes32_to_bytesn(&env, &tp.ad_chain_token),
        &tp.amount,
        &tp.order_chain_id,
        &bytes32_to_bytesn(&env, &tp.ad_recipient),
    );

    TestSetup {
        env,
        tp,
        ad_manager,
        order_portal,
        admin_addr,
        ad_token_addr,
        order_token_addr,
    }
}

// ===========================================================================
// Helpers: build contract OrderParams from TestParams
// ===========================================================================

fn ad_manager_order_params(env: &Env, tp: &TestParams) -> ad_manager_contract::OrderParams {
    ad_manager_contract::OrderParams {
        order_chain_token: bytes32_to_bytesn(env, &tp.order_chain_token),
        ad_chain_token: bytes32_to_bytesn(env, &tp.ad_chain_token),
        amount: tp.amount,
        bridger: bytes32_to_bytesn(env, &tp.bridger),
        order_chain_id: tp.order_chain_id,
        src_order_portal: bytes32_to_bytesn(env, &tp.order_portal_id),
        order_recipient: bytes32_to_bytesn(env, &tp.order_recipient),
        ad_id: SorobanString::from_str(env, &tp.ad_id),
        ad_creator: bytes32_to_bytesn(env, &tp.ad_creator),
        ad_recipient: bytes32_to_bytesn(env, &tp.ad_recipient),
        salt: soroban_sdk::U256::from_u128(env, tp.salt),
        order_decimals: tp.order_decimals,
        ad_decimals: tp.ad_decimals,
        deadline: tp.deadline,
        ad_settlement_signer: bytes32_to_bytesn(env, &tp.ad_settlement_signer),
    }
}

fn order_portal_order_params(env: &Env, tp: &TestParams) -> order_portal_contract::OrderParams {
    order_portal_contract::OrderParams {
        order_chain_token: bytes32_to_bytesn(env, &tp.order_chain_token),
        ad_chain_token: bytes32_to_bytesn(env, &tp.ad_chain_token),
        amount: tp.amount,
        bridger: bytes32_to_bytesn(env, &tp.bridger),
        order_recipient: bytes32_to_bytesn(env, &tp.order_recipient),
        ad_chain_id: tp.ad_chain_id,
        ad_manager: bytes32_to_bytesn(env, &tp.ad_manager_id),
        ad_id: SorobanString::from_str(env, &tp.ad_id),
        ad_creator: bytes32_to_bytesn(env, &tp.ad_creator),
        ad_recipient: bytes32_to_bytesn(env, &tp.ad_recipient),
        salt: soroban_sdk::U256::from_u128(env, tp.salt),
        order_decimals: tp.order_decimals,
        ad_decimals: tp.ad_decimals,
        deadline: tp.deadline,
        ad_settlement_signer: bytes32_to_bytesn(env, &tp.ad_settlement_signer),
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[test]
fn test_ad_manager_lock_for_order() {
    let s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    let order_hash = s.ad_manager.lock_for_order(&params);

    // Verify the order hash matches fixture
    assert_eq!(
        order_hash,
        bytes32_to_bytesn(&s.env, &s.tp.order_hash),
        "Ad-manager order hash must match fixture"
    );

    // Ad-manager appends side 0 ⇒ its own root is the ad-chain root.
    let root = s.ad_manager.get_latest_merkle_root();
    assert_eq!(
        root,
        bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        "Ad-manager merkle root must match ad_root"
    );

    // Verify order status is Open
    assert_eq!(
        s.ad_manager.get_order_status(&order_hash),
        ad_manager_contract::Status::Open,
    );
}

#[test]
fn test_ad_manager_unlock_with_bridger_proof() {
    let s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    // Lock first
    s.ad_manager.lock_for_order(&params);

    // Bridger proves inclusion in the counterparty (order-chain) root.
    s.ad_manager.unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.order_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );

    // Verify order is now Filled
    let order_hash = bytes32_to_bytesn(&s.env, &s.tp.order_hash);
    assert_eq!(
        s.ad_manager.get_order_status(&order_hash),
        ad_manager_contract::Status::Filled,
    );
}

#[test]
fn test_order_portal_create_and_unlock() {
    let s = setup();

    // Mint tokens to bridger
    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let order_token_client = TokenContractClient::new(&s.env, &s.order_token_addr);
    order_token_client.mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let params = order_portal_order_params(&s.env, &s.tp);

    let order_hash = s.order_portal.create_order(&params);

    assert_eq!(
        order_hash,
        bytes32_to_bytesn(&s.env, &s.tp.order_hash),
        "Order-portal order hash must match fixture"
    );
    assert_eq!(
        s.order_portal.get_order_status(&order_hash),
        order_portal_contract::Status::Open,
    );

    // Ad-creator proves inclusion in the counterparty (ad-chain) root.
    s.order_portal.unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    );

    assert_eq!(
        s.order_portal.get_order_status(&order_hash),
        order_portal_contract::Status::Filled,
    );
}

// Permissionless unlock: no external address's auth is required — env.auths()
// after the call is empty (the removed recipient require_auth would appear here).
#[test]
fn test_order_portal_unlock_is_permissionless() {
    let s = setup();

    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    TokenContractClient::new(&s.env, &s.order_token_addr)
        .mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let params = order_portal_order_params(&s.env, &s.tp);
    s.order_portal.create_order(&params);

    s.order_portal.unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    );

    assert!(
        s.env.auths().is_empty(),
        "unlock must require no address auth (recipient gate removed)"
    );
    assert_eq!(
        s.order_portal
            .get_order_status(&bytes32_to_bytesn(&s.env, &s.tp.order_hash)),
        order_portal_contract::Status::Filled,
    );
}

#[test]
fn test_ad_manager_unlock_is_permissionless() {
    let s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    s.ad_manager.lock_for_order(&params);

    s.ad_manager.unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.order_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );

    assert!(
        s.env.auths().is_empty(),
        "unlock must require no address auth (recipient gate removed)"
    );
    assert_eq!(
        s.ad_manager
            .get_order_status(&bytes32_to_bytesn(&s.env, &s.tp.order_hash)),
        ad_manager_contract::Status::Filled,
    );
}

#[test]
fn test_full_cross_chain_flow() {
    let s = setup();

    // ----- AD CHAIN: lock order -----
    let ad_params = ad_manager_order_params(&s.env, &s.tp);

    let ad_order_hash = s.ad_manager.lock_for_order(&ad_params);

    // ----- ORDER CHAIN: create order -----
    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let order_token_client = TokenContractClient::new(&s.env, &s.order_token_addr);
    order_token_client.mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let order_params = order_portal_order_params(&s.env, &s.tp);

    let order_hash = s.order_portal.create_order(&order_params);

    // Both chains compute the same order hash
    assert_eq!(
        ad_order_hash, order_hash,
        "Order hash must be identical on both chains"
    );

    // ----- AD CHAIN: bridger unlocks proving the order-chain (counterparty) root -----
    let bridger_target_root = s.order_portal.get_latest_merkle_root();

    s.ad_manager.unlock(
        &ad_params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bridger_target_root,
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );

    assert_eq!(
        s.ad_manager.get_order_status(&order_hash),
        ad_manager_contract::Status::Filled,
    );

    // ----- ORDER CHAIN: ad creator unlocks proving the ad-chain (counterparty) root -----
    let adcreator_target_root = s.ad_manager.get_latest_merkle_root();

    s.order_portal.unlock(
        &order_params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &adcreator_target_root,
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    );

    assert_eq!(
        s.order_portal.get_order_status(&order_hash),
        order_portal_contract::Status::Filled,
    );
}

#[test]
fn test_nullifier_prevents_double_unlock() {
    let s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    // Lock
    s.ad_manager.lock_for_order(&params);

    // First unlock succeeds (bridger proves the order-chain root)
    s.ad_manager.unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.order_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );

    // Second unlock should fail (order already filled)
    let result = s.ad_manager.try_unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.order_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );

    assert!(result.is_err(), "Double unlock must fail");
}

// ============================================================================
// Gate 2 — root-verification module wiring (1.2c)
// ============================================================================

mod counterparty_verifier_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/counterparty_verifier.wasm");
}

mod bls_key_registry_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/bls_key_registry.wasm");
}

#[soroban_sdk::contract]
pub struct MockRootVerifier;

#[soroban_sdk::contractimpl]
impl MockRootVerifier {
    pub fn set_ok(env: Env, ok: bool) {
        env.storage()
            .instance()
            .set(&soroban_sdk::symbol_short!("ok"), &ok);
    }

    pub fn is_root_valid(
        env: Env,
        _source_chain_id: u128,
        _root: BytesN<32>,
        _metadata: Bytes,
    ) -> bool {
        env.storage()
            .instance()
            .get(&soroban_sdk::symbol_short!("ok"))
            .unwrap_or(false)
    }
}

fn locked_ad_order(s: &TestSetup) -> ad_manager_contract::OrderParams {
    let params = ad_manager_order_params(&s.env, &s.tp);
    s.ad_manager.lock_for_order(&params);
    params
}

fn ad_unlock(s: &TestSetup, params: &ad_manager_contract::OrderParams, cosig: &Bytes) -> bool {
    s.ad_manager
        .try_unlock(
            params,
            &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
            &bytes32_to_bytesn(&s.env, &s.tp.order_root),
            &Bytes::from_slice(&s.env, PROOF_BRIDGER),
            cosig,
        )
        .is_ok()
}

#[test]
fn test_gate2_mock_true_unlocks_and_clears_in_flight() {
    let s = setup();
    let params = locked_ad_order(&s);

    let mock = s.env.register(MockRootVerifier, ());
    MockRootVerifierClient::new(&s.env, &mock).set_ok(&true);
    s.ad_manager.set_root_verifier(&s.tp.order_chain_id, &mock);

    assert!(s.ad_manager.has_open_positions(&params.ad_creator));
    assert!(s.ad_manager.has_open_positions(&params.bridger));

    let empty = Bytes::new(&s.env);
    assert!(ad_unlock(&s, &params, &empty));

    assert!(!s.ad_manager.has_open_positions(&params.ad_creator));
    assert!(!s.ad_manager.has_open_positions(&params.bridger));
}

#[test]
fn test_gate2_mock_false_blocks_unlock() {
    let s = setup();
    let params = locked_ad_order(&s);

    let mock = s.env.register(MockRootVerifier, ());
    MockRootVerifierClient::new(&s.env, &mock).set_ok(&false);
    s.ad_manager.set_root_verifier(&s.tp.order_chain_id, &mock);

    let empty = Bytes::new(&s.env);
    assert!(!ad_unlock(&s, &params, &empty));
}

/// The gate is mandatory: with no root-verifier module configured for the
/// route, unlock must fail (RootVerifierNotSet) even with a valid proof.
#[test]
fn test_unlock_fails_without_root_verifier() {
    let s = setup_with_verifiers(false);
    let params = locked_ad_order(&s);

    let res = s.ad_manager.try_unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.order_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );
    assert_eq!(
        res,
        Err(Ok(ad_manager_contract::AdManagerError::RootVerifierNotSet)),
        "unlock must fail with RootVerifierNotSet when no module is configured"
    );
}

#[test]
fn test_gate2_real_module_rejects_root_outside_signed_auth() {
    let s = setup();
    let params = locked_ad_order(&s);

    // Real module C wired to a dummy registry: the fixture's target root is
    // not inside the vector SettlementAuth, so it fails before any lookup.
    let module = s.env.register(counterparty_verifier_contract::WASM, ());
    counterparty_verifier_contract::Client::new(&s.env, &module).initialize(&s.ad_manager.address);
    s.ad_manager
        .set_root_verifier(&s.tp.order_chain_id, &module);

    let vectors: serde_json::Value =
        serde_json::from_str(include_str!("../../test-vectors/bls-encodings.json")).unwrap();
    let hexv =
        |v: &serde_json::Value| hex::decode(v.as_str().unwrap().trim_start_matches("0x")).unwrap();
    let auth = &vectors["settlement"]["auth"];
    let mut cosig = std::vec![2u8]; // metadata v2
    let ocid: u128 = auth["orderChainId"].as_str().unwrap().parse().unwrap();
    let acid: u128 = auth["adChainId"].as_str().unwrap().parse().unwrap();
    cosig.extend_from_slice(&ocid.to_be_bytes());
    cosig.extend_from_slice(&acid.to_be_bytes());
    cosig.extend_from_slice(&hexv(&auth["orderHash"]));
    cosig.extend_from_slice(&hexv(&auth["orderChainRoot"]));
    cosig.extend_from_slice(&hexv(&auth["adChainRoot"]));
    cosig.extend_from_slice(&0u32.to_be_bytes()); // maker slot id
    cosig.extend_from_slice(&0u32.to_be_bytes()); // bridger slot id
    cosig.extend_from_slice(&hexv(&vectors["keys"]["makerBls"]["pk"]["uncompressed"]));
    cosig.extend_from_slice(&hexv(&vectors["keys"]["bridgerBls"]["pk"]["uncompressed"]));
    cosig.extend_from_slice(&hexv(&vectors["settlement"]["aggSig"]["uncompressed"]));

    let cosig_bytes = Bytes::from_slice(&s.env, &cosig);
    assert!(!ad_unlock(&s, &params, &cosig_bytes));
}

#[test]
fn test_gate2_garbage_cosig_blocks_unlock() {
    let s = setup();
    let params = locked_ad_order(&s);

    let module = s.env.register(counterparty_verifier_contract::WASM, ());
    counterparty_verifier_contract::Client::new(&s.env, &module).initialize(&s.ad_manager.address);
    s.ad_manager
        .set_root_verifier(&s.tp.order_chain_id, &module);

    let garbage = Bytes::from_slice(&s.env, &[0xde, 0xad]);
    assert!(!ad_unlock(&s, &params, &garbage));
}

#[test]
fn test_gate2_portal_mock_false_blocks_unlock() {
    let s = setup();

    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    TokenContractClient::new(&s.env, &s.order_token_addr)
        .mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let params = order_portal_order_params(&s.env, &s.tp);
    s.order_portal.create_order(&params);

    let mock = s.env.register(MockRootVerifier, ());
    MockRootVerifierClient::new(&s.env, &mock).set_ok(&false);
    s.order_portal.set_root_verifier(&s.tp.ad_chain_id, &mock);

    let res = s.order_portal.try_unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    );
    assert!(res.is_err(), "portal unlock must fail gate 2");
}

// ============================================================================
// Pause + two-step admin (1.2g)
// ============================================================================

#[test]
fn test_pause_blocks_lock_and_unlock_until_unpause() {
    let s = setup();

    s.ad_manager.pause();

    let params = ad_manager_order_params(&s.env, &s.tp);
    let res = s.ad_manager.try_lock_for_order(&params);
    assert!(res.is_err(), "lock must fail while paused");

    s.ad_manager.unpause();
    s.ad_manager.lock_for_order(&params);

    s.ad_manager.pause();
    let empty = Bytes::new(&s.env);
    assert!(
        !ad_unlock(&s, &params, &empty),
        "unlock must fail while paused"
    );

    s.ad_manager.unpause();
    let empty = Bytes::new(&s.env);
    assert!(ad_unlock(&s, &params, &empty));
}

#[test]
fn test_pause_blocks_create_order() {
    let s = setup();

    s.order_portal.pause();

    let params = order_portal_order_params(&s.env, &s.tp);
    let res = s.order_portal.try_create_order(&params);
    assert!(res.is_err(), "create must fail while paused");
}

#[test]
fn test_two_step_admin_transfer() {
    let s = setup();

    assert!(s.ad_manager.try_accept_admin().is_err());

    let next = Address::generate(&s.env);
    s.ad_manager.transfer_admin(&next);
    s.ad_manager.accept_admin();

    s.ad_manager.pause();
    s.ad_manager.unpause();
}

// ============================================================================
// Pull-payment escrow (1.2h)
// ============================================================================

#[test]
fn test_payout_pushes_directly_when_recipient_ok() {
    let s = setup();
    let params = locked_ad_order(&s);

    let recipient_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.order_recipient).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let token_client = TokenContractClient::new(&s.env, &s.ad_token_addr);
    let before = token_client.balance(&recipient_addr);

    let empty = Bytes::new(&s.env);
    assert!(ad_unlock(&s, &params, &empty));

    assert!(
        token_client.balance(&recipient_addr) > before,
        "happy path must pay directly"
    );

    let recipient = bytes32_to_bytesn(&s.env, &s.tp.order_recipient);
    let token = bytes32_to_bytesn(&s.env, &s.tp.ad_chain_token);
    let res = s.ad_manager.try_claim(&recipient, &token);
    assert!(res.is_err(), "nothing to claim after a direct payout");
}

#[test]
fn test_payout_falls_back_to_credit_then_claims_once() {
    let s = setup();
    let params = locked_ad_order(&s);

    let recipient_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.order_recipient).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let token_client = TokenContractClient::new(&s.env, &s.ad_token_addr);
    let before = token_client.balance(&recipient_addr);

    // recipient's token refuses transfers: unlock must still settle
    token_client.set_fail_transfers(&true);
    let empty = Bytes::new(&s.env);
    assert!(
        ad_unlock(&s, &params, &empty),
        "unlock blocked by payout failure"
    );
    assert_eq!(
        token_client.balance(&recipient_addr),
        before,
        "push should have failed"
    );

    let recipient = bytes32_to_bytesn(&s.env, &s.tp.order_recipient);
    let token = bytes32_to_bytesn(&s.env, &s.tp.ad_chain_token);

    // still failing: the credit stays parked
    assert!(s.ad_manager.try_claim(&recipient, &token).is_err());
    assert_eq!(token_client.balance(&recipient_addr), before);

    // token recovers: claim pays exactly once
    token_client.set_fail_transfers(&false);
    s.ad_manager.claim(&recipient, &token);
    assert!(
        token_client.balance(&recipient_addr) > before,
        "claim did not pay"
    );

    let res = s.ad_manager.try_claim(&recipient, &token);
    assert!(res.is_err(), "second claim must fail");
}

#[test]
fn test_portal_payout_pushes_directly() {
    let s = setup();

    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    TokenContractClient::new(&s.env, &s.order_token_addr)
        .mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let params = order_portal_order_params(&s.env, &s.tp);
    s.order_portal.create_order(&params);

    let recipient_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.ad_recipient).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let token_client = TokenContractClient::new(&s.env, &s.order_token_addr);
    let before = token_client.balance(&recipient_addr);

    s.order_portal.unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    );

    assert!(
        token_client.balance(&recipient_addr) > before,
        "portal payout must push directly"
    );
    let res = s.order_portal.try_claim(
        &bytes32_to_bytesn(&s.env, &s.tp.ad_recipient),
        &bytes32_to_bytesn(&s.env, &s.tp.order_chain_token),
    );
    assert!(res.is_err(), "nothing to claim after a direct payout");
}

// ============================================================================
// Position guards — the real escrows plug into the registry
// ============================================================================

// Revoke must round-trip through BOTH real escrows cross-contract: a live
// locked trade keeps them busy while an uninvolved account revokes cleanly.
#[test]
fn test_registry_guards_are_the_real_escrows() {
    let s = setup();
    let params = locked_ad_order(&s);

    let vectors: serde_json::Value =
        serde_json::from_str(include_str!("../../test-vectors/bls-encodings.json")).unwrap();
    let hexv =
        |v: &serde_json::Value| hex::decode(v.as_str().unwrap().trim_start_matches("0x")).unwrap();

    // pin the registry at the contract id the vector PoPs bind
    let regid: [u8; 32] = hexv(&vectors["chains"]["stellarTestnet"]["registryId"])
        .try_into()
        .unwrap();
    let at = Address::from_string(&SorobanString::from_str(
        &s.env,
        &stellar_strkey::Contract(regid).to_string(),
    ));
    let registry = s.env.register_at(&at, bls_key_registry_contract::WASM, ());
    let client = bls_key_registry_contract::Client::new(&s.env, &registry);
    let chain_id: u128 = vectors["chains"]["stellarTestnet"]["chainId"]
        .as_str()
        .unwrap()
        .parse()
        .unwrap();
    client.initialize(&s.admin_addr, &chain_id);

    client.set_position_guards(&soroban_sdk::vec![
        &s.env,
        s.ad_manager.address.clone(),
        s.order_portal.address.clone()
    ]);

    // register the vector maker key (Stellar-home: require_auth, mocked)
    let r = &vectors["registration"]["makerOnStellarTestnet"];
    let account = BytesN::from_array(&s.env, &hexv(&r["account"]).try_into().unwrap());
    let wallet_pk: [u8; 32] = hexv(&vectors["keys"]["makerWallet"]["pk"])
        .try_into()
        .unwrap();
    let owner = Address::from_string(&SorobanString::from_str(
        &s.env,
        &stellar_strkey::ed25519::PublicKey(wallet_pk).to_string(),
    ));
    let pk = BytesN::from_array(&s.env, &hexv(&r["pkNative"]).try_into().unwrap());
    let pop = BytesN::from_array(&s.env, &hexv(&r["pop"]).try_into().unwrap());
    client.register(
        &account,
        &bls_key_registry_contract::OwnerAuth::Stellar(owner.clone()),
        &pk,
        &pop,
        &0,
    );

    // the fixture trade genuinely occupies both guard sources...
    assert!(s.ad_manager.has_open_positions(&params.ad_creator));
    assert!(!s.order_portal.has_open_positions(&account));

    // ...and the revoke round-trips through BOTH real escrows and passes
    client.revoke(
        &account,
        &bls_key_registry_contract::OwnerAuth::Stellar(owner),
        &1,
    );
    assert!(client.try_commitment_at(&account, &0).is_err());
}

// 1.6c cost-measurement gate: CPU instructions + memory bytes consumed by a full
// WASM unlock on each escrow (real ZK verify via cross-contract call). Metered
// with reset_unlimited() immediately before the call; asserts <= in-source ceiling.
// Run: cargo test --test integration_test test_unlock_metering -- --nocapture
#[test]
fn test_unlock_metering() {
    // Ad-manager unlock (bridger proof against order-chain root).
    {
        let s = setup();
        let params = ad_manager_order_params(&s.env, &s.tp);
        s.ad_manager.lock_for_order(&params);

        s.env.cost_estimate().budget().reset_unlimited();
        s.ad_manager.unlock(
            &params,
            &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
            &bytes32_to_bytesn(&s.env, &s.tp.order_root),
            &Bytes::from_slice(&s.env, PROOF_BRIDGER),
            &Bytes::new(&s.env),
        );
        let b = s.env.cost_estimate().budget();
        let (cpu, mem) = (b.cpu_instruction_cost(), b.memory_bytes_cost());
        std::println!("ad_manager.unlock: cpu {} insns, mem {} bytes", cpu, mem);
        assert!(cpu <= AD_UNLOCK_CPU_CEILING);
        assert!(mem <= AD_UNLOCK_MEM_CEILING);
    }

    // Order-portal unlock (ad-creator proof against ad-chain root).
    {
        let s = setup();
        let bridger_addr = {
            let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
            Address::from_string(&SorobanString::from_str(&s.env, &strkey))
        };
        TokenContractClient::new(&s.env, &s.order_token_addr)
            .mint(&bridger_addr, &(s.tp.amount as i128 * 10));

        let params = order_portal_order_params(&s.env, &s.tp);
        s.order_portal.create_order(&params);

        s.env.cost_estimate().budget().reset_unlimited();
        s.order_portal.unlock(
            &params,
            &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
            &bytes32_to_bytesn(&s.env, &s.tp.ad_root),
            &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
            &Bytes::new(&s.env),
        );
        let b = s.env.cost_estimate().budget();
        let (cpu, mem) = (b.cpu_instruction_cost(), b.memory_bytes_cost());
        std::println!("order_portal.unlock: cpu {} insns, mem {} bytes", cpu, mem);
        assert!(cpu <= OP_UNLOCK_CPU_CEILING);
        assert!(mem <= OP_UNLOCK_MEM_CEILING);
    }
}

// ---------------------------------------------------------------------------
// Event claims (2.3d): the same circuit and the same verify_proof as deposits; the contract-built
// public inputs (proofbridge_core::cross_contract::build_event_public_inputs) keep them apart.
// ---------------------------------------------------------------------------

use proofbridge_core::cross_contract::{
    build_event_public_inputs, build_public_inputs as build_deposit_inputs, LEAF_DOMAIN_AD,
    LEAF_DOMAIN_CANCEL, LEAF_DOMAIN_REGISTERED, LEAF_DOMAIN_SETTLED,
};

const EVENT_CLAIMS: [(u32, &[u8]); 3] = [
    (
        LEAF_DOMAIN_CANCEL,
        include_bytes!("fixtures/event_claim_2.bin"),
    ),
    (
        LEAF_DOMAIN_SETTLED,
        include_bytes!("fixtures/event_claim_3.bin"),
    ),
    (
        LEAF_DOMAIN_REGISTERED,
        include_bytes!("fixtures/event_claim_4.bin"),
    ),
];

struct EventSetup<'a> {
    env: Env,
    verifier: verifier_contract::Client<'a>,
    merkle: Address,
    tp: TestParams,
}

fn event_setup() -> EventSetup<'static> {
    let env = Env::default();
    env.mock_all_auths_allowing_non_root_auth();
    env.cost_estimate().budget().reset_unlimited();
    let verifier_id = env.register(VERIFIER_WASM, (Bytes::from_slice(&env, VK),));
    let merkle = env.register(MERKLE_WASM, ());
    merkle_contract::Client::new(&env, &merkle).initialize(&Address::generate(&env));
    let verifier = verifier_contract::Client::new(&env, &verifier_id);
    EventSetup {
        env,
        verifier,
        merkle,
        tp: load_test_params(),
    }
}

fn event_root(s: &EventSetup, domain: u32) -> BytesN<32> {
    bytes32_to_bytesn(&s.env, &s.tp.event_roots[(domain - 2) as usize])
}

#[test]
fn test_event_claims_verify_for_every_event_domain() {
    let s = event_setup();
    let order_hash = bytes32_to_bytesn(&s.env, &s.tp.order_hash);
    for (domain, proof) in EVENT_CLAIMS {
        let inputs = build_event_public_inputs(
            &s.env,
            &s.merkle,
            &event_root(&s, domain),
            &order_hash,
            domain,
        );
        s.verifier
            .verify_proof(&inputs, &Bytes::from_slice(&s.env, proof));
    }
}

#[test]
fn test_event_claim_rejected_under_another_domain_or_as_a_deposit() {
    let s = event_setup();
    let order_hash = bytes32_to_bytesn(&s.env, &s.tp.order_hash);
    let root = event_root(&s, LEAF_DOMAIN_CANCEL);
    let proof = Bytes::from_slice(&s.env, EVENT_CLAIMS[0].1);

    let other_domain =
        build_event_public_inputs(&s.env, &s.merkle, &root, &order_hash, LEAF_DOMAIN_SETTLED);
    assert!(s.verifier.try_verify_proof(&other_domain, &proof).is_err());

    let zero = BytesN::from_array(&s.env, &[0u8; 32]);
    let as_deposit = build_deposit_inputs(
        &s.env,
        &s.merkle,
        &zero,
        &root,
        &order_hash,
        LEAF_DOMAIN_AD as u8,
    );
    assert!(s.verifier.try_verify_proof(&as_deposit, &proof).is_err());
}

#[test]
fn test_deposit_proof_rejected_as_an_event_claim() {
    let s = event_setup();
    let order_hash = bytes32_to_bytesn(&s.env, &s.tp.order_hash);
    let order_root = bytes32_to_bytesn(&s.env, &s.tp.order_root);
    let inputs = build_event_public_inputs(
        &s.env,
        &s.merkle,
        &order_root,
        &order_hash,
        LEAF_DOMAIN_CANCEL,
    );
    assert!(s
        .verifier
        .try_verify_proof(&inputs, &Bytes::from_slice(&s.env, PROOF_BRIDGER))
        .is_err());
}

// ---------------------------------------------------------------------------
// T-26 (2.3d D6): replays ../../test-vectors/verifier-negative.json against the verifier wasm. Each
// vector is a real proof with byte patches; it must verify or fail exactly as recorded.
// ---------------------------------------------------------------------------

const VERIFIER_NEGATIVE_JSON: &str = include_str!("../../test-vectors/verifier-negative.json");

#[derive(Deserialize)]
struct NegativeFile {
    #[serde(rename = "_meta")]
    meta: NegativeMeta,
    bases: std::collections::BTreeMap<std::string::String, NegativeBase>,
    vectors: std::vec::Vec<NegativeVector>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct NegativeMeta {
    vk_keccak: std::string::String,
}

#[derive(Deserialize)]
struct NegativeBase {
    proof: std::string::String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct NegativeVector {
    name: std::string::String,
    base: std::string::String,
    patch_offsets: std::vec::Vec<usize>,
    patch_words: std::vec::Vec<std::string::String>,
    proof_length: usize,
    public_inputs: std::vec::Vec<std::string::String>,
    expect: std::string::String,
}

fn unhex(s: &str) -> std::vec::Vec<u8> {
    hex::decode(s.trim_start_matches("0x")).unwrap()
}

#[test]
fn test_t26_verifier_negative_vectors() {
    use sha3::{Digest, Keccak256};
    let file: NegativeFile = serde_json::from_str(VERIFIER_NEGATIVE_JSON).unwrap();
    assert_eq!(
        std::format!("0x{}", hex::encode(Keccak256::digest(VK))),
        file.meta.vk_keccak,
        "the vectors were made with another key: regenerate them (bls-vectors gen:verifier-negative)"
    );

    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let id = env.register(VERIFIER_WASM, (Bytes::from_slice(&env, VK),));
    let verifier = verifier_contract::Client::new(&env, &id);

    assert!(!file.vectors.is_empty());
    for v in &file.vectors {
        let mut proof = unhex(&file.bases[&v.base].proof);
        for (off, w) in v.patch_offsets.iter().zip(&v.patch_words) {
            proof[*off..*off + 32].copy_from_slice(&unhex(w));
        }
        proof.truncate(v.proof_length);
        let inputs: std::vec::Vec<u8> = v.public_inputs.iter().flat_map(|w| unhex(w)).collect();
        let result = verifier.try_verify_proof(
            &Bytes::from_slice(&env, &inputs),
            &Bytes::from_slice(&env, &proof),
        );
        let accepted = matches!(result, Ok(Ok(())));
        assert_eq!(
            accepted,
            v.expect == "accept",
            "{}: expected {}",
            v.name,
            v.expect
        );
    }
}

// ---------------------------------------------------------------------------
// 2.3b: the envelope's slot 0 is the order's ad_settlement_signer. The fixture is a split case
// (settlement signer != custody address), the only shape in which a wrong slot shows.
// ---------------------------------------------------------------------------

#[soroban_sdk::contract]
pub struct Slot0RootVerifier;

#[soroban_sdk::contractimpl]
impl Slot0RootVerifier {
    pub fn expect(env: Env, slot0: BytesN<32>) {
        env.storage()
            .instance()
            .set(&soroban_sdk::symbol_short!("slot0"), &slot0);
    }

    pub fn is_root_valid(
        env: Env,
        _source_chain_id: u128,
        _root: BytesN<32>,
        metadata: Bytes,
    ) -> bool {
        let expected: BytesN<32> = env
            .storage()
            .instance()
            .get(&soroban_sdk::symbol_short!("slot0"))
            .unwrap();
        metadata.len() >= 32
            && BytesN::<32>::try_from(metadata.slice(0..32))
                .map(|head| head == expected)
                .unwrap_or(false)
    }
}

fn slot0_module(s: &TestSetup, expected: &BytesN<32>) -> Address {
    let module = s.env.register(Slot0RootVerifier, ());
    Slot0RootVerifierClient::new(&s.env, &module).expect(expected);
    module
}

fn created_portal_order(s: &TestSetup) -> order_portal_contract::OrderParams {
    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    TokenContractClient::new(&s.env, &s.order_token_addr)
        .mint(&bridger_addr, &(s.tp.amount as i128 * 10));
    let params = order_portal_order_params(&s.env, &s.tp);
    s.order_portal.create_order(&params);
    params
}

fn portal_unlock(
    s: &TestSetup,
    params: &order_portal_contract::OrderParams,
) -> Result<(), order_portal_contract::OrderPortalError> {
    match s.order_portal.try_unlock(
        params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.ad_root),
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
        &Bytes::new(&s.env),
    ) {
        Ok(_) => Ok(()),
        Err(Ok(e)) => Err(e),
        Err(Err(_)) => panic!("unlock failed with a host error"),
    }
}

#[test]
fn test_split_case_ad_manager_unlock_resolves_the_settlement_signer() {
    let s = setup();
    let params = locked_ad_order(&s);
    assert_ne!(
        params.ad_settlement_signer, params.ad_creator,
        "the fixture must be a split case"
    );

    let custody = slot0_module(&s, &params.ad_creator);
    s.ad_manager
        .set_root_verifier(&s.tp.order_chain_id, &custody);
    assert!(!ad_unlock(&s, &params, &Bytes::new(&s.env)));

    let signer = slot0_module(&s, &params.ad_settlement_signer);
    s.ad_manager
        .set_root_verifier(&s.tp.order_chain_id, &signer);
    assert!(ad_unlock(&s, &params, &Bytes::new(&s.env)));
}

#[test]
fn test_split_case_order_portal_unlock_resolves_the_settlement_signer() {
    let s = setup();
    let params = created_portal_order(&s);
    assert_ne!(
        params.ad_settlement_signer, params.ad_creator,
        "the fixture must be a split case"
    );

    let custody = slot0_module(&s, &params.ad_creator);
    s.order_portal
        .set_root_verifier(&s.tp.ad_chain_id, &custody);
    assert_eq!(
        portal_unlock(&s, &params),
        Err(order_portal_contract::OrderPortalError::RootNotValid)
    );

    let signer = slot0_module(&s, &params.ad_settlement_signer);
    s.order_portal.set_root_verifier(&s.tp.ad_chain_id, &signer);
    assert_eq!(portal_unlock(&s, &params), Ok(()));
}

#[test]
fn test_ad_manager_unlock_after_deadline_is_rejected() {
    use soroban_sdk::testutils::Ledger;
    let s = setup();
    let params = locked_ad_order(&s);
    let module = slot0_module(&s, &params.ad_settlement_signer);
    s.ad_manager
        .set_root_verifier(&s.tp.order_chain_id, &module);

    s.env.ledger().set_timestamp(params.deadline + 1);
    let late = s.ad_manager.try_unlock(
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.order_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
        &Bytes::new(&s.env),
    );
    assert_eq!(
        late,
        Err(Ok(ad_manager_contract::AdManagerError::OrderExpired))
    );

    s.env.ledger().set_timestamp(params.deadline);
    assert!(ad_unlock(&s, &params, &Bytes::new(&s.env)));
}

#[test]
fn test_order_portal_unlock_after_deadline_is_rejected() {
    use soroban_sdk::testutils::Ledger;
    let s = setup();
    let params = created_portal_order(&s);
    let module = slot0_module(&s, &params.ad_settlement_signer);
    s.order_portal.set_root_verifier(&s.tp.ad_chain_id, &module);

    s.env.ledger().set_timestamp(params.deadline + 1);
    assert_eq!(
        portal_unlock(&s, &params),
        Err(order_portal_contract::OrderPortalError::OrderExpired)
    );
    s.env.ledger().set_timestamp(params.deadline);
    assert_eq!(portal_unlock(&s, &params), Ok(()));
}
