//! ProofBridge Stellar integration tests
//!
//! Tests the full contract flow: deploy all 4 contracts, create ads, lock
//! orders, and unlock with ZK proofs — going through the ad-manager and
//! order-portal contracts exactly as real-world usage would.
//!
//! Fixtures are pre-generated by tests/fixtures/generate_fixtures.ts using
//! deterministic contract addresses so the EIP-712 order hashes match.
//! Proof-derived values (order hash, target root, nullifiers) are read from
//! test_params.json so regenerating fixtures doesn't require code changes.

extern crate std;

use ed25519_dalek::{Signer, SigningKey};
use serde::Deserialize;
use sha3::{Digest, Keccak256};
use soroban_sdk::{
    contract, contractimpl, Address, Bytes, BytesN, Env, MuxedAddress, String as SorobanString,
};
use stellar_strkey::Contract;
use stellar_tokens::fungible::{Base, FungibleToken};

// ---------------------------------------------------------------------------
// WASM blobs
// ---------------------------------------------------------------------------

const VERIFIER_WASM: &[u8] = include_bytes!("../target/wasm32v1-none/release/verifier.wasm");
const MERKLE_WASM: &[u8] = include_bytes!("../target/wasm32v1-none/release/merkle_manager.wasm");
const AD_MANAGER_WASM: &[u8] = include_bytes!("../target/wasm32v1-none/release/ad_manager.wasm");
const ORDER_PORTAL_WASM: &[u8] =
    include_bytes!("../target/wasm32v1-none/release/order_portal.wasm");

// ---------------------------------------------------------------------------
// Inline SAC-convention token contract (stellar-tokens)
// ---------------------------------------------------------------------------

#[contract]
pub struct TokenContract;

#[contractimpl]
impl TokenContract {
    pub fn __constructor(e: &Env, owner: Address, initial_supply: i128) {
        Base::mint(e, &owner, initial_supply);
    }

    pub fn mint(e: &Env, to: Address, amount: i128) {
        Base::mint(e, &to, amount);
    }
}

#[contractimpl(contracttrait)]
impl FungibleToken for TokenContract {
    type ContractType = Base;
}

// ---------------------------------------------------------------------------
// Contract imports (typed Client wrappers)
// ---------------------------------------------------------------------------

mod verifier_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/verifier.wasm");
}

mod merkle_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/merkle_manager.wasm");
}

mod ad_manager_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/ad_manager.wasm");
}

mod order_portal_contract {
    soroban_sdk::contractimport!(file = "target/wasm32v1-none/release/order_portal.wasm");
}

// ---------------------------------------------------------------------------
// Proof fixtures (binary, generated by tests/fixtures/generate_fixtures.ts)
// ---------------------------------------------------------------------------

const VK: &[u8] = include_bytes!("fixtures/vk");
const PROOF_BRIDGER: &[u8] = include_bytes!("fixtures/proof_bridger.bin");
const PROOF_AD_CREATOR: &[u8] = include_bytes!("fixtures/proof_ad_creator.bin");

// ---------------------------------------------------------------------------
// Test parameters loaded from JSON (generated by generate_fixtures.ts)
// ---------------------------------------------------------------------------

const TEST_PARAMS_JSON: &str = include_str!("fixtures/test_params.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
struct TestParamsJson {
    secret: String,
    order_hash: String,
    order_hash_mod: String,
    target_root: String,
    bridger_nullifier: String,
    ad_creator_nullifier: String,
    element_index: u64,
    width: u64,
    contract_addresses: ContractAddressesJson,
    order_params: OrderParamsJson,
    chain_ids: ChainIdsJson,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ContractAddressesJson {
    ad_manager: String,
    order_portal: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
struct OrderParamsJson {
    order_chain_token: String,
    ad_chain_token: String,
    amount: String,
    bridger: String,
    order_chain_id: String,
    order_portal: String,
    order_recipient: String,
    ad_chain_id: String,
    ad_manager: String,
    ad_id: String,
    ad_creator: String,
    ad_recipient: String,
    salt: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ChainIdsJson {
    order_chain_id: u128,
    ad_chain_id: u128,
}

/// Parsed test parameters with raw byte arrays ready for use.
struct TestParams {
    order_hash: [u8; 32],
    target_root: [u8; 32],
    bridger_nullifier: [u8; 32],
    ad_creator_nullifier: [u8; 32],
    // Contract addresses
    ad_manager_id: [u8; 32],
    order_portal_id: [u8; 32],
    // Order fields
    order_chain_token: [u8; 32],
    ad_chain_token: [u8; 32],
    amount: u128,
    bridger: [u8; 32],
    order_recipient: [u8; 32],
    ad_creator: [u8; 32],
    ad_recipient: [u8; 32],
    salt: u128,
    ad_id: std::string::String,
    // Chain IDs
    order_chain_id: u128,
    ad_chain_id: u128,
}

fn hex_to_array(hex_str: &str) -> [u8; 32] {
    let clean = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    let mut arr = [0u8; 32];
    hex::decode_to_slice(clean, &mut arr).unwrap();
    arr
}

/// Decode a Stellar strkey address (C... or G...) to its 32-byte payload
fn strkey_to_array(strkey: &str) -> [u8; 32] {
    if strkey.starts_with('C') {
        stellar_strkey::Contract::from_string(strkey)
            .expect("invalid C... address")
            .0
    } else if strkey.starts_with('G') {
        stellar_strkey::ed25519::PublicKey::from_string(strkey)
            .expect("invalid G... address")
            .0
    } else {
        panic!("Unknown strkey prefix: {}", strkey);
    }
}

fn load_test_params() -> TestParams {
    let json: TestParamsJson = serde_json::from_str(TEST_PARAMS_JSON).unwrap();
    TestParams {
        // These remain 0x hex (proof-derived values)
        order_hash: hex_to_array(&json.order_hash),
        target_root: hex_to_array(&json.target_root),
        bridger_nullifier: hex_to_array(&json.bridger_nullifier),
        ad_creator_nullifier: hex_to_array(&json.ad_creator_nullifier),
        // Contract addresses (C... strkey format)
        ad_manager_id: strkey_to_array(&json.contract_addresses.ad_manager),
        order_portal_id: strkey_to_array(&json.contract_addresses.order_portal),
        // Token addresses (C... strkey format)
        order_chain_token: strkey_to_array(&json.order_params.order_chain_token),
        ad_chain_token: strkey_to_array(&json.order_params.ad_chain_token),
        amount: json.order_params.amount.parse().unwrap(),
        // User addresses (G... strkey format)
        bridger: strkey_to_array(&json.order_params.bridger),
        order_recipient: strkey_to_array(&json.order_params.order_recipient),
        ad_creator: strkey_to_array(&json.order_params.ad_creator),
        ad_recipient: strkey_to_array(&json.order_params.ad_recipient),
        salt: json.order_params.salt.parse().unwrap(),
        ad_id: json.order_params.ad_id,
        order_chain_id: json.chain_ids.order_chain_id,
        ad_chain_id: json.chain_ids.ad_chain_id,
    }
}

// ---------------------------------------------------------------------------
// Keccak256 + request hash helpers (mirrors proofbridge-core/src/auth.rs)
// ---------------------------------------------------------------------------

fn keccak256(data: &[u8]) -> [u8; 32] {
    let mut hasher = Keccak256::new();
    hasher.update(data);
    hasher.finalize().into()
}

/// Replicate proofbridge_core::auth::hash_string_field
fn hash_string_field(s: &str) -> [u8; 32] {
    keccak256(s.as_bytes())
}

/// Replicate proofbridge_core::auth::hash_request
fn hash_request(
    auth_token: &[u8; 32],
    time_to_expire: u64,
    action: &str,
    params: &[u8],
    chain_id: u128,
    contract_address: &[u8; 32],
) -> [u8; 32] {
    let mut buf = [0u8; 512];
    let mut offset = 0;

    buf[offset..offset + 32].copy_from_slice(auth_token);
    offset += 32;

    buf[offset..offset + 8].copy_from_slice(&time_to_expire.to_be_bytes());
    offset += 8;

    let action_hash = keccak256(action.as_bytes());
    buf[offset..offset + 32].copy_from_slice(&action_hash);
    offset += 32;

    buf[offset..offset + params.len()].copy_from_slice(params);
    offset += params.len();

    buf[offset..offset + 16].copy_from_slice(&chain_id.to_be_bytes());
    offset += 16;

    buf[offset..offset + 32].copy_from_slice(contract_address);
    offset += 32;

    keccak256(&buf[..offset])
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn bytes32_to_bytesn(env: &Env, arr: &[u8; 32]) -> BytesN<32> {
    BytesN::from_array(env, arr)
}

/// Create an Address from a 32-byte contract ID
fn contract_address(env: &Env, id: &[u8; 32]) -> Address {
    let strkey = Contract(*id).to_string();
    let soroban_str = SorobanString::from_str(env, &strkey);
    Address::from_string(&soroban_str)
}

/// Generate an ed25519 keypair and derive the Stellar account address
fn generate_signer(env: &Env) -> (SigningKey, BytesN<32>, Address) {
    let mut rng = rand::thread_rng();
    let signing_key = SigningKey::generate(&mut rng);
    let pubkey_bytes = signing_key.verifying_key().to_bytes();
    let pub_bytes32 = BytesN::from_array(env, &pubkey_bytes);

    let strkey = stellar_strkey::ed25519::PublicKey(pubkey_bytes).to_string();
    let soroban_str = SorobanString::from_str(env, &strkey);
    let address = Address::from_string(&soroban_str);

    (signing_key, pub_bytes32, address)
}

/// Sign a 32-byte message hash with ed25519, returning a BytesN<64> signature
fn ed25519_sign(env: &Env, signing_key: &SigningKey, message_hash: &[u8; 32]) -> BytesN<64> {
    let sig = signing_key.sign(message_hash);
    BytesN::from_array(env, &sig.to_bytes())
}

/// Counter for unique auth tokens
struct AuthTokenCounter(u8);

impl AuthTokenCounter {
    fn new() -> Self {
        Self(1)
    }

    fn next(&mut self) -> [u8; 32] {
        let mut token = [0u8; 32];
        token[0] = self.0;
        self.0 += 1;
        token
    }
}

// ---------------------------------------------------------------------------
// Test setup
// ---------------------------------------------------------------------------

#[allow(dead_code)]
struct TestSetup<'a> {
    env: Env,
    // Fixture params (loaded from test_params.json)
    tp: TestParams,
    // Contracts
    ad_manager: ad_manager_contract::Client<'a>,
    order_portal: order_portal_contract::Client<'a>,
    // Admin signer
    signing_key: SigningKey,
    admin_pubkey: BytesN<32>,
    admin_addr: Address,
    // Token addresses (deployed test-token contracts)
    ad_token_addr: Address,
    order_token_addr: Address,
    // Auth token counter (each call needs unique token)
    auth_counter: AuthTokenCounter,
}

impl<'a> TestSetup<'a> {
    /// Sign a request for the ad-manager (computes hash then signs)
    fn sign_ad_manager_request(
        &mut self,
        action: &str,
        params: &[u8],
    ) -> (BytesN<64>, BytesN<32>, u64) {
        let auth_token = self.auth_counter.next();
        let time_to_expire = u64::MAX;

        let message_hash = hash_request(
            &auth_token,
            time_to_expire,
            action,
            params,
            self.tp.ad_chain_id,
            &self.tp.ad_manager_id,
        );

        let signature = ed25519_sign(&self.env, &self.signing_key, &message_hash);
        let auth_token_bn = BytesN::from_array(&self.env, &auth_token);

        (signature, auth_token_bn, time_to_expire)
    }

    /// Sign a request for the order-portal
    fn sign_order_portal_request(
        &mut self,
        action: &str,
        params: &[u8],
    ) -> (BytesN<64>, BytesN<32>, u64) {
        let auth_token = self.auth_counter.next();
        let time_to_expire = u64::MAX;

        let message_hash = hash_request(
            &auth_token,
            time_to_expire,
            action,
            params,
            self.tp.order_chain_id,
            &self.tp.order_portal_id,
        );

        let signature = ed25519_sign(&self.env, &self.signing_key, &message_hash);
        let auth_token_bn = BytesN::from_array(&self.env, &auth_token);

        (signature, auth_token_bn, time_to_expire)
    }
}

fn setup() -> TestSetup<'static> {
    let tp = load_test_params();

    let env = Env::default();
    env.mock_all_auths_allowing_non_root_auth();
    env.cost_estimate().budget().reset_unlimited();

    let mut auth_counter = AuthTokenCounter::new();

    // Generate admin keypair
    let (signing_key, admin_pubkey, admin_addr) = generate_signer(&env);

    // Deploy verifiers
    let vk_bytes = Bytes::from_slice(&env, VK);
    let ad_verifier_id = env.register(VERIFIER_WASM, (vk_bytes.clone(),));
    let order_verifier_id = env.register(VERIFIER_WASM, (vk_bytes,));

    // Deploy merkle managers
    let ad_merkle_id = env.register(MERKLE_WASM, ());
    let ad_merkle = merkle_contract::Client::new(&env, &ad_merkle_id);
    ad_merkle.initialize(&admin_addr);

    let order_merkle_id = env.register(MERKLE_WASM, ());
    let order_merkle = merkle_contract::Client::new(&env, &order_merkle_id);
    order_merkle.initialize(&admin_addr);

    // Deploy ad-manager at deterministic address
    let ad_manager_addr = contract_address(&env, &tp.ad_manager_id);
    env.register_at(&ad_manager_addr, AD_MANAGER_WASM, ());
    let ad_manager = ad_manager_contract::Client::new(&env, &ad_manager_addr);

    // Deploy order-portal at deterministic address
    let order_portal_addr = contract_address(&env, &tp.order_portal_id);
    env.register_at(&order_portal_addr, ORDER_PORTAL_WASM, ());
    let order_portal = order_portal_contract::Client::new(&env, &order_portal_addr);

    // Deploy SAC-convention tokens at deterministic addresses matching fixture params.
    // Both contracts resolve BytesN<32> → Contract address → token::Client
    let ad_token_addr = contract_address(&env, &tp.ad_chain_token);
    env.register_at(&ad_token_addr, TokenContract, (admin_addr.clone(), 0i128));

    let order_token_addr = contract_address(&env, &tp.order_chain_token);
    env.register_at(&order_token_addr, TokenContract, (admin_addr.clone(), 0i128));

    // w_native_token is required by the constructor but not used for non-native tokens
    let w_native_token = ad_token_addr.clone();

    // Initialize contracts (uses require_auth, mocked)
    ad_manager.initialize(
        &admin_addr,
        &ad_verifier_id,
        &ad_merkle_id,
        &w_native_token,
        &tp.ad_chain_id,
    );
    order_portal.initialize(
        &admin_addr,
        &order_verifier_id,
        &order_merkle_id,
        &order_token_addr,
        &tp.order_chain_id,
    );

    // Set merkle managers
    ad_merkle.set_manager(&ad_manager_addr, &true);
    order_merkle.set_manager(&order_portal_addr, &true);

    // --- Ad-manager: set_chain (ed25519 signed) ---
    {
        let auth_token = auth_counter.next();
        let time_to_expire = u64::MAX;
        let message_hash = hash_request(
            &auth_token,
            time_to_expire,
            "setChain",
            &[],
            tp.ad_chain_id,
            &tp.ad_manager_id,
        );
        let signature = ed25519_sign(&env, &signing_key, &message_hash);
        let auth_token_bn = BytesN::from_array(&env, &auth_token);

        ad_manager.set_chain(
            &signature,
            &admin_pubkey,
            &auth_token_bn,
            &time_to_expire,
            &tp.order_chain_id,
            &bytes32_to_bytesn(&env, &tp.order_portal_id),
            &true,
        );
    }

    // --- Order-portal: set_chain (uses require_auth, mocked) ---
    order_portal.set_chain(
        &tp.ad_chain_id,
        &bytes32_to_bytesn(&env, &tp.ad_manager_id),
        &true,
    );

    // --- Ad-manager: set_token_route (ed25519 signed) ---
    {
        let auth_token = auth_counter.next();
        let time_to_expire = u64::MAX;
        let message_hash = hash_request(
            &auth_token,
            time_to_expire,
            "setTokenRoute",
            &[],
            tp.ad_chain_id,
            &tp.ad_manager_id,
        );
        let signature = ed25519_sign(&env, &signing_key, &message_hash);
        let auth_token_bn = BytesN::from_array(&env, &auth_token);

        ad_manager.set_token_route(
            &signature,
            &admin_pubkey,
            &auth_token_bn,
            &time_to_expire,
            &bytes32_to_bytesn(&env, &tp.ad_chain_token),
            &bytes32_to_bytesn(&env, &tp.order_chain_token),
            &tp.order_chain_id,
        );
    }

    // --- Order-portal: set_token_route (uses require_auth, mocked) ---
    order_portal.set_token_route(
        &bytes32_to_bytesn(&env, &tp.order_chain_token),
        &tp.ad_chain_id,
        &bytes32_to_bytesn(&env, &tp.ad_chain_token),
    );

    // Mint tokens to admin via the SAC-convention token
    let ad_token_client = TokenContractClient::new(&env, &ad_token_addr);
    ad_token_client.mint(&admin_addr, &(tp.amount as i128 * 10));

    // --- Ad-manager: create_ad (ed25519 signed) ---
    {
        let auth_token = auth_counter.next();
        let time_to_expire = u64::MAX;

        // params: ad_id_hash(32) + ad_token(32) + initial_amount(16) + order_chain_id(16) + ad_recipient(32) = 128
        let mut params = [0u8; 128];
        let ad_id_hash = hash_string_field(&tp.ad_id);
        params[0..32].copy_from_slice(&ad_id_hash);
        params[32..64].copy_from_slice(&tp.ad_chain_token);
        params[64..80].copy_from_slice(&tp.amount.to_be_bytes());
        params[80..96].copy_from_slice(&tp.order_chain_id.to_be_bytes());
        params[96..128].copy_from_slice(&tp.ad_recipient);

        let message_hash = hash_request(
            &auth_token,
            time_to_expire,
            "createAd",
            &params,
            tp.ad_chain_id,
            &tp.ad_manager_id,
        );
        let signature = ed25519_sign(&env, &signing_key, &message_hash);
        let auth_token_bn = BytesN::from_array(&env, &auth_token);

        ad_manager.create_ad(
            &signature,
            &admin_pubkey,
            &auth_token_bn,
            &time_to_expire,
            &SorobanString::from_str(&env, &tp.ad_id),
            &bytes32_to_bytesn(&env, &tp.ad_chain_token),
            &tp.amount,
            &tp.order_chain_id,
            &bytes32_to_bytesn(&env, &tp.ad_recipient),
        );
    }

    TestSetup {
        env,
        tp,
        ad_manager,
        order_portal,
        signing_key,
        admin_pubkey,
        admin_addr,
        ad_token_addr,
        order_token_addr,
        auth_counter,
    }
}

// ===========================================================================
// Helper: build request hash params for various actions
// ===========================================================================

fn lock_for_order_params(ad_id: &str, order_hash: &[u8; 32]) -> [u8; 64] {
    let mut params = [0u8; 64];
    params[0..32].copy_from_slice(&hash_string_field(ad_id));
    params[32..64].copy_from_slice(order_hash);
    params
}

fn unlock_order_params(ad_id: &str, order_hash: &[u8; 32], target_root: &[u8; 32]) -> [u8; 96] {
    let mut params = [0u8; 96];
    params[0..32].copy_from_slice(&hash_string_field(ad_id));
    params[32..64].copy_from_slice(order_hash);
    params[64..96].copy_from_slice(target_root);
    params
}

fn create_order_params(ad_id: &str, order_hash: &[u8; 32]) -> [u8; 64] {
    let mut params = [0u8; 64];
    params[0..32].copy_from_slice(&hash_string_field(ad_id));
    params[32..64].copy_from_slice(order_hash);
    params
}

// ===========================================================================
// Helpers: build contract OrderParams from TestParams
// ===========================================================================

fn ad_manager_order_params(env: &Env, tp: &TestParams) -> ad_manager_contract::OrderParams {
    ad_manager_contract::OrderParams {
        order_chain_token: bytes32_to_bytesn(env, &tp.order_chain_token),
        ad_chain_token: bytes32_to_bytesn(env, &tp.ad_chain_token),
        amount: tp.amount,
        bridger: bytes32_to_bytesn(env, &tp.bridger),
        order_chain_id: tp.order_chain_id,
        src_order_portal: bytes32_to_bytesn(env, &tp.order_portal_id),
        order_recipient: bytes32_to_bytesn(env, &tp.order_recipient),
        ad_id: SorobanString::from_str(env, &tp.ad_id),
        ad_creator: bytes32_to_bytesn(env, &tp.ad_creator),
        ad_recipient: bytes32_to_bytesn(env, &tp.ad_recipient),
        salt: tp.salt,
    }
}

fn order_portal_order_params(env: &Env, tp: &TestParams) -> order_portal_contract::OrderParams {
    order_portal_contract::OrderParams {
        order_chain_token: bytes32_to_bytesn(env, &tp.order_chain_token),
        ad_chain_token: bytes32_to_bytesn(env, &tp.ad_chain_token),
        amount: tp.amount,
        bridger: bytes32_to_bytesn(env, &tp.bridger),
        order_recipient: bytes32_to_bytesn(env, &tp.order_recipient),
        ad_chain_id: tp.ad_chain_id,
        ad_manager: bytes32_to_bytesn(env, &tp.ad_manager_id),
        ad_id: SorobanString::from_str(env, &tp.ad_id),
        ad_creator: bytes32_to_bytesn(env, &tp.ad_creator),
        ad_recipient: bytes32_to_bytesn(env, &tp.ad_recipient),
        salt: tp.salt,
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[test]
fn test_ad_manager_lock_for_order() {
    let mut s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    // Sign lockForOrder
    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (signature, auth_token, time_to_expire) =
        s.sign_ad_manager_request("lockForOrder", &lock_params);

    let order_hash = s.ad_manager.lock_for_order(
        &signature,
        &s.admin_pubkey,
        &auth_token,
        &time_to_expire,
        &params,
    );

    // Verify the order hash matches fixture
    assert_eq!(
        order_hash,
        bytes32_to_bytesn(&s.env, &s.tp.order_hash),
        "Ad-manager order hash must match fixture"
    );

    // Verify merkle root matches
    let root = s.ad_manager.get_latest_merkle_root();
    assert_eq!(
        root,
        bytes32_to_bytesn(&s.env, &s.tp.target_root),
        "Merkle root must match fixture"
    );

    // Verify order status is Open
    assert_eq!(
        s.ad_manager.get_order_status(&order_hash),
        ad_manager_contract::Status::Open,
    );
}

#[test]
fn test_ad_manager_unlock_with_bridger_proof() {
    let mut s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    // Lock first
    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_ad_manager_request("lockForOrder", &lock_params);
    s.ad_manager
        .lock_for_order(&sig, &s.admin_pubkey, &tok, &exp, &params);

    // Unlock with bridger proof
    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.target_root);
    let (sig, tok, exp) = s.sign_ad_manager_request("unlockOrder", &unlock_params);

    s.ad_manager.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.target_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
    );

    // Verify order is now Filled
    let order_hash = bytes32_to_bytesn(&s.env, &s.tp.order_hash);
    assert_eq!(
        s.ad_manager.get_order_status(&order_hash),
        ad_manager_contract::Status::Filled,
    );
}

#[test]
fn test_order_portal_create_and_unlock() {
    let mut s = setup();

    // Mint tokens to bridger
    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let order_token_client = TokenContractClient::new(&s.env, &s.order_token_addr);
    order_token_client.mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let params = order_portal_order_params(&s.env, &s.tp);

    // Sign createOrder
    let create_params = create_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_order_portal_request("createOrder", &create_params);

    let order_hash = s
        .order_portal
        .create_order(&sig, &s.admin_pubkey, &tok, &exp, &params);

    assert_eq!(
        order_hash,
        bytes32_to_bytesn(&s.env, &s.tp.order_hash),
        "Order-portal order hash must match fixture"
    );
    assert_eq!(
        s.order_portal.get_order_status(&order_hash),
        order_portal_contract::Status::Open,
    );

    // Unlock with ad-creator proof
    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.target_root);
    let (sig, tok, exp) = s.sign_order_portal_request("unlockOrder", &unlock_params);

    s.order_portal.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.target_root),
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
    );

    assert_eq!(
        s.order_portal.get_order_status(&order_hash),
        order_portal_contract::Status::Filled,
    );
}

#[test]
fn test_full_cross_chain_flow() {
    let mut s = setup();

    // ----- AD CHAIN: lock order -----
    let ad_params = ad_manager_order_params(&s.env, &s.tp);

    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_ad_manager_request("lockForOrder", &lock_params);

    let ad_order_hash = s
        .ad_manager
        .lock_for_order(&sig, &s.admin_pubkey, &tok, &exp, &ad_params);

    // ----- ORDER CHAIN: create order -----
    let bridger_addr = {
        let strkey = stellar_strkey::ed25519::PublicKey(s.tp.bridger).to_string();
        Address::from_string(&SorobanString::from_str(&s.env, &strkey))
    };
    let order_token_client = TokenContractClient::new(&s.env, &s.order_token_addr);
    order_token_client.mint(&bridger_addr, &(s.tp.amount as i128 * 10));

    let order_params = order_portal_order_params(&s.env, &s.tp);

    let create_params = create_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_order_portal_request("createOrder", &create_params);

    let order_hash = s
        .order_portal
        .create_order(&sig, &s.admin_pubkey, &tok, &exp, &order_params);

    // Both chains compute the same order hash
    assert_eq!(
        ad_order_hash, order_hash,
        "Order hash must be identical on both chains"
    );

    // ----- AD CHAIN: bridger unlocks with proof -----
    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.target_root);
    let (sig, tok, exp) = s.sign_ad_manager_request("unlockOrder", &unlock_params);

    s.ad_manager.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &ad_params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &s.ad_manager.get_latest_merkle_root(),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
    );

    assert_eq!(
        s.ad_manager.get_order_status(&order_hash),
        ad_manager_contract::Status::Filled,
    );

    // ----- ORDER CHAIN: ad creator unlocks with proof -----
    let order_target_root = s.order_portal.get_latest_merkle_root();
    let order_target_root_arr = order_target_root.to_array();
    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &order_target_root_arr);
    let (sig, tok, exp) = s.sign_order_portal_request("unlockOrder", &unlock_params);

    s.order_portal.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &order_params,
        &bytes32_to_bytesn(&s.env, &s.tp.ad_creator_nullifier),
        &order_target_root,
        &Bytes::from_slice(&s.env, PROOF_AD_CREATOR),
    );

    assert_eq!(
        s.order_portal.get_order_status(&order_hash),
        order_portal_contract::Status::Filled,
    );
}

#[test]
fn test_nullifier_prevents_double_unlock() {
    let mut s = setup();
    let params = ad_manager_order_params(&s.env, &s.tp);

    // Lock
    let lock_params = lock_for_order_params(&s.tp.ad_id, &s.tp.order_hash);
    let (sig, tok, exp) = s.sign_ad_manager_request("lockForOrder", &lock_params);
    s.ad_manager
        .lock_for_order(&sig, &s.admin_pubkey, &tok, &exp, &params);

    // First unlock succeeds
    let unlock_params = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.target_root);
    let (sig, tok, exp) = s.sign_ad_manager_request("unlockOrder", &unlock_params);

    s.ad_manager.unlock(
        &sig,
        &s.admin_pubkey,
        &tok,
        &exp,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.target_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
    );

    // Second unlock should fail (order already filled)
    let unlock_params2 = unlock_order_params(&s.tp.ad_id, &s.tp.order_hash, &s.tp.target_root);
    let (sig2, tok2, exp2) = s.sign_ad_manager_request("unlockOrder", &unlock_params2);

    let result = s.ad_manager.try_unlock(
        &sig2,
        &s.admin_pubkey,
        &tok2,
        &exp2,
        &params,
        &bytes32_to_bytesn(&s.env, &s.tp.bridger_nullifier),
        &bytes32_to_bytesn(&s.env, &s.tp.target_root),
        &Bytes::from_slice(&s.env, PROOF_BRIDGER),
    );

    assert!(result.is_err(), "Double unlock must fail");
}
