[package]
name = "agent-account"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
proofbridge-core = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils", "alloc"] }
ad-manager = { path = "../ad-manager", features = ["testutils"] }
merkle-manager = { path = "../merkle-manager", features = ["testutils"] }
test-token = { path = "../test-token", features = ["testutils"] }
ed25519-dalek = { workspace = true }
k256 = { version = "0.13", features = ["ecdsa"] }

[features]
testutils = ["soroban-sdk/testutils"]
